//! Tests that compare Rust curve outputs against values produced by the actual
//! Solidity contracts running inside Forge.
//!
//! Fixture file: `tests/fixtures/onchain_parity.json`
//! Generated by: `contracts/core/tests/unit/curves/GenerateParityFixtures.t.sol`
//!
//! Regenerate:
//!   cd contracts/core && FOUNDRY_PROFILE=test forge test --mt test_generateParityFixtures -vv

use std::{collections::HashMap, fs, path::PathBuf, str::FromStr};

use curves::{
    fee_on_raw, preview_atom_deposit, preview_redeem_with_fees, preview_triple_deposit, AtomFees,
    Curve, CurveState, FeeSchedule, LinearCurve, OffsetProgressiveCurve, TripleFees, U256,
};

type Map = HashMap<String, serde_json::Value>;

fn fixtures() -> HashMap<String, Map> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/onchain_parity.json");
    serde_json::from_str(&fs::read_to_string(path).expect("fixture file should exist"))
        .expect("fixture json should deserialize")
}

fn val(section: &Map, key: &str) -> U256 {
    let s = section[key]
        .as_str()
        .unwrap_or_else(|| panic!("fixture key '{key}' should be a string"));
    U256::from_str(s).unwrap_or_else(|_| panic!("fixture key '{key}' should parse as U256"))
}

fn one() -> U256 {
    U256::from(1_000_000_000_000_000_000u128)
}

// =====================================================================
// LinearCurve parity — every value from the on-chain fixture
// =====================================================================

#[test]
fn linear_onchain_parity() {
    let all = fixtures();
    let f = &all["linear"];
    let curve = LinearCurve::new();

    // max_shares / max_assets
    assert_eq!(curve.max_shares(), val(f, "max_shares"), "max_shares");
    assert_eq!(curve.max_assets(), val(f, "max_assets"), "max_assets");

    // preview_deposit — zero state
    assert_eq!(
        curve.preview_deposit(one(), CurveState::default()).unwrap(),
        val(f, "deposit_zero_1e18"),
        "deposit_zero_1e18"
    );
    assert_eq!(
        curve
            .preview_deposit(U256::from(1u64), CurveState::default())
            .unwrap(),
        val(f, "deposit_zero_1"),
        "deposit_zero_1"
    );
    assert_eq!(
        curve
            .preview_deposit(U256::from(1_000_000u64), CurveState::default())
            .unwrap(),
        val(f, "deposit_zero_1e6"),
        "deposit_zero_1e6"
    );

    // preview_deposit — with state
    assert_eq!(
        curve
            .preview_deposit(
                one(),
                CurveState {
                    total_assets: U256::from(10u64) * one(),
                    total_shares: U256::from(5u64) * one(),
                }
            )
            .unwrap(),
        val(f, "deposit_10e18_5e18_1e18"),
        "deposit_10e18_5e18_1e18"
    );
    assert_eq!(
        curve
            .preview_deposit(
                U256::from(25u64) * one(),
                CurveState {
                    total_assets: U256::from(100u64) * one(),
                    total_shares: U256::from(50u64) * one(),
                }
            )
            .unwrap(),
        val(f, "deposit_100e18_50e18_25e18"),
        "deposit_100e18_50e18_25e18"
    );

    // preview_mint (rounds up)
    assert_eq!(
        curve
            .preview_mint(
                one(),
                CurveState {
                    total_assets: U256::from(3_000_000_000_000_000_001u128),
                    total_shares: U256::from(2u64) * one(),
                }
            )
            .unwrap(),
        val(f, "mint_3e18p1_2e18_1e18"),
        "mint_3e18p1_2e18_1e18"
    );
    assert_eq!(
        curve.preview_mint(one(), CurveState::default()).unwrap(),
        val(f, "mint_zero_1e18"),
        "mint_zero_1e18"
    );

    // preview_redeem
    assert_eq!(
        curve
            .preview_redeem(
                one(),
                CurveState {
                    total_assets: U256::from(10u64) * one(),
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "redeem_10e18_10e18_1e18"),
        "redeem_10e18_10e18_1e18"
    );
    assert_eq!(
        curve
            .preview_redeem(
                one(),
                CurveState {
                    total_assets: U256::from(20u64) * one(),
                    total_shares: U256::from(5u64) * one(),
                }
            )
            .unwrap(),
        val(f, "redeem_5e18_20e18_1e18"),
        "redeem_5e18_20e18_1e18"
    );
    assert_eq!(
        curve
            .preview_redeem(
                U256::from(5u64) * one(),
                CurveState {
                    total_assets: U256::from(10u64) * one(),
                    total_shares: U256::from(5u64) * one(),
                }
            )
            .unwrap(),
        val(f, "redeem_all_5e18_10e18"),
        "redeem_all_5e18_10e18"
    );

    // preview_withdraw (rounds up)
    assert_eq!(
        curve
            .preview_withdraw(
                one(),
                CurveState {
                    total_assets: U256::from(3u64) * one(),
                    total_shares: U256::from(2u64) * one(),
                }
            )
            .unwrap(),
        val(f, "withdraw_3e18_2e18_1e18"),
        "withdraw_3e18_2e18_1e18"
    );

    // current_price
    assert_eq!(
        curve
            .current_price(CurveState {
                total_assets: one(),
                total_shares: one(),
            })
            .unwrap(),
        val(f, "price_1e18_1e18"),
        "price_1e18_1e18"
    );
    assert_eq!(
        curve
            .current_price(CurveState {
                total_assets: U256::MAX,
                total_shares: U256::MAX,
            })
            .unwrap(),
        val(f, "price_max_max"),
        "price_max_max"
    );
    assert_eq!(
        curve
            .current_price(CurveState {
                total_assets: U256::from(10u64) * one(),
                total_shares: U256::from(5u64) * one(),
            })
            .unwrap(),
        val(f, "price_5e18_10e18"),
        "price_5e18_10e18"
    );
}

// =====================================================================
// OffsetProgressiveCurve parity — slope=2e18, offset=0.5e18
// =====================================================================

#[test]
fn progressive_onchain_parity() {
    let all = fixtures();
    let f = &all["progressive"];

    let slope = val(f, "slope");
    let offset = val(f, "offset");
    let curve = OffsetProgressiveCurve::new(slope, offset).unwrap();

    // max bounds
    assert_eq!(curve.max_shares(), val(f, "max_shares"), "max_shares");
    assert_eq!(curve.max_assets(), val(f, "max_assets"), "max_assets");

    // preview_deposit from zero — 1 wei to 1000 ETH
    for (amount, key) in [
        (U256::from(1u64), "deposit_zero_1"),
        (U256::from(1_000_000u64), "deposit_zero_1e6"),
        (one(), "deposit_zero_1e18"),
        (U256::from(100u64) * one(), "deposit_zero_100e18"),
        (U256::from(1000u64) * one(), "deposit_zero_1000e18"),
    ] {
        assert_eq!(
            curve
                .preview_deposit(amount, CurveState::default())
                .unwrap(),
            val(f, key),
            "{key}"
        );
    }

    // preview_deposit with state
    assert_eq!(
        curve
            .preview_deposit(
                one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "deposit_0_10e18_1e18"),
        "deposit_0_10e18_1e18"
    );
    assert_eq!(
        curve
            .preview_deposit(
                U256::from(50u64) * one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(100u64) * one(),
                }
            )
            .unwrap(),
        val(f, "deposit_0_100e18_50e18"),
        "deposit_0_100e18_50e18"
    );
    assert_eq!(
        curve
            .preview_deposit(
                U256::from(100u64) * one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "deposit_0_10e18_100e18"),
        "deposit_0_10e18_100e18"
    );

    // preview_mint (rounds up)
    assert_eq!(
        curve
            .preview_mint(
                one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "mint_0_10e18_1e18"),
        "mint_0_10e18_1e18"
    );
    assert_eq!(
        curve
            .preview_mint(
                U256::from(5u64) * one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "mint_0_10e18_5e18"),
        "mint_0_10e18_5e18"
    );
    assert_eq!(
        curve.preview_mint(one(), CurveState::default()).unwrap(),
        val(f, "mint_0_0_1e18"),
        "mint_0_0_1e18"
    );

    // preview_redeem
    assert_eq!(
        curve
            .preview_redeem(
                one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "redeem_0_10e18_1e18"),
        "redeem_0_10e18_1e18"
    );
    assert_eq!(
        curve
            .preview_redeem(
                U256::from(5u64) * one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "redeem_0_10e18_5e18"),
        "redeem_0_10e18_5e18"
    );
    assert_eq!(
        curve
            .preview_redeem(
                U256::from(10u64) * one(),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "redeem_0_10e18_10e18"),
        "redeem_0_10e18_10e18"
    );

    // preview_withdraw
    assert_eq!(
        curve
            .preview_withdraw(
                one(),
                CurveState {
                    total_assets: one(),
                    total_shares: U256::from(10u64) * one(),
                }
            )
            .unwrap(),
        val(f, "withdraw_1e18_10e18_1e18"),
        "withdraw_1e18_10e18_1e18"
    );
    assert_eq!(
        curve
            .preview_withdraw(
                U256::from(50u64) * one(),
                CurveState {
                    total_assets: U256::from(50u64) * one(),
                    total_shares: U256::from(100u64) * one(),
                }
            )
            .unwrap(),
        val(f, "withdraw_50e18_100e18_50e18"),
        "withdraw_50e18_100e18_50e18"
    );

    // current_price
    assert_eq!(
        curve.current_price(CurveState::default()).unwrap(),
        val(f, "price_0"),
        "price_0"
    );
    assert_eq!(
        curve
            .current_price(CurveState {
                total_assets: U256::ZERO,
                total_shares: U256::from(10u64) * one(),
            })
            .unwrap(),
        val(f, "price_10e18"),
        "price_10e18"
    );
    assert_eq!(
        curve
            .current_price(CurveState {
                total_assets: U256::ZERO,
                total_shares: U256::from(100u64) * one(),
            })
            .unwrap(),
        val(f, "price_100e18"),
        "price_100e18"
    );
    assert_eq!(
        curve
            .current_price(CurveState {
                total_assets: U256::ZERO,
                total_shares: U256::from(1000u64) * one(),
            })
            .unwrap(),
        val(f, "price_1000e18"),
        "price_1000e18"
    );
}

// =====================================================================
// Zero-offset progressive curve parity
// =====================================================================

#[test]
fn progressive_zero_offset_onchain_parity() {
    let all = fixtures();
    let f = &all["progressive_zero_offset"];
    let slope = U256::from(2_000_000_000_000_000_000u128);
    let curve = OffsetProgressiveCurve::new(slope, U256::ZERO).unwrap();

    assert_eq!(curve.max_shares(), val(f, "max_shares"), "max_shares");
    assert_eq!(curve.max_assets(), val(f, "max_assets"), "max_assets");
    assert_eq!(
        curve.current_price(CurveState::default()).unwrap(),
        val(f, "price_0"),
        "price_0"
    );
    assert_eq!(
        curve.preview_deposit(one(), CurveState::default()).unwrap(),
        val(f, "deposit_zero_1e18"),
        "deposit_zero_1e18"
    );
    assert_eq!(
        curve
            .preview_deposit(U256::from(100u64) * one(), CurveState::default())
            .unwrap(),
        val(f, "deposit_zero_100e18"),
        "deposit_zero_100e18"
    );
    assert_eq!(
        curve
            .preview_redeem(
                U256::from(699_560_508u64),
                CurveState {
                    total_assets: U256::ZERO,
                    total_shares: U256::from(700_560_508u64),
                }
            )
            .unwrap(),
        val(f, "redeem_low_shares"),
        "redeem_low_shares"
    );
}

// =====================================================================
// Fee calculation parity — matches MultiVault._feeOnRaw exactly
// =====================================================================

#[test]
fn fee_on_raw_matches_solidity_mul_div_up() {
    let all = fixtures();
    let f = &all["fees"];
    let denom = U256::from(10_000u64);

    // Individual fee calculations
    for (amount, bps, key) in [
        (one(), 100u64, "fee_1e18_100bps"),
        (one(), 50, "fee_1e18_50bps"),
        (one(), 25, "fee_1e18_25bps"),
        (one(), 200, "fee_1e18_200bps"),
        (U256::from(1000u64), 100, "fee_1000_100bps"),
        (U256::from(1u64), 100, "fee_1_100bps"),
        (U256::from(1000u64) * one(), 100, "fee_1000e18_100bps"),
        (one(), 0, "fee_1e18_0bps"),
        (U256::from(1u64), 50, "fee_1_50bps"),
        (U256::from(1u64), 25, "fee_1_25bps"),
    ] {
        assert_eq!(
            fee_on_raw(amount, U256::from(bps), denom).unwrap(),
            val(f, key),
            "{key}"
        );
    }
}

// =====================================================================
// Atom deposit fee simulation — protocol + entry + wallet
// =====================================================================

#[test]
fn atom_deposit_fees_match_solidity() {
    let all = fixtures();
    let f = &all["fees"];
    let denom = U256::from(10_000u64);
    let amount = U256::from(10u64) * one();

    // Verify individual fee components
    let protocol = fee_on_raw(amount, U256::from(100u64), denom).unwrap();
    let entry = fee_on_raw(amount, U256::from(50u64), denom).unwrap();
    let wallet = fee_on_raw(amount, U256::from(25u64), denom).unwrap();

    assert_eq!(protocol, val(f, "atom_10e18_protocol"), "protocol");
    assert_eq!(entry, val(f, "atom_10e18_entry"), "entry");
    assert_eq!(wallet, val(f, "atom_10e18_wallet"), "wallet");

    // Verify combined via preview_atom_deposit
    let curve = LinearCurve::new();
    let state = CurveState {
        total_assets: U256::from(100u64) * one(),
        total_shares: U256::from(100u64) * one(),
    };
    let fees = FeeSchedule {
        denominator: denom,
        protocol_fee: U256::from(100u64),
        entry_fee: U256::from(50u64),
        exit_fee: U256::from(25u64),
    };
    let atom_fees = AtomFees {
        atom_wallet_deposit_fee: U256::from(25u64),
    };

    let quote = preview_atom_deposit(&curve, amount, state, fees, atom_fees, true).unwrap();
    assert_eq!(quote.fees.protocol_fee, protocol);
    assert_eq!(quote.fees.entry_fee, entry);
    assert_eq!(quote.fees.atom_wallet_fee, wallet);
    assert_eq!(
        quote.assets_after_fees,
        amount - protocol - entry - wallet,
        "net assets"
    );
}

// =====================================================================
// Triple deposit fee simulation — protocol + entry + atom fraction
// =====================================================================

#[test]
fn triple_deposit_fees_match_solidity() {
    let all = fixtures();
    let f = &all["fees"];
    let denom = U256::from(10_000u64);
    let amount = U256::from(10u64) * one();

    let protocol = fee_on_raw(amount, U256::from(100u64), denom).unwrap();
    let entry = fee_on_raw(amount, U256::from(50u64), denom).unwrap();
    let atom_fraction = fee_on_raw(amount, U256::from(150u64), denom).unwrap();

    assert_eq!(protocol, val(f, "triple_10e18_protocol"), "protocol");
    assert_eq!(entry, val(f, "triple_10e18_entry"), "entry");
    assert_eq!(
        atom_fraction,
        val(f, "triple_10e18_atom_fraction"),
        "atom_fraction"
    );

    // Verify combined
    let curve = LinearCurve::new();
    let state = CurveState {
        total_assets: U256::from(100u64) * one(),
        total_shares: U256::from(100u64) * one(),
    };
    let fees = FeeSchedule {
        denominator: denom,
        protocol_fee: U256::from(100u64),
        entry_fee: U256::from(50u64),
        exit_fee: U256::from(25u64),
    };
    let triple_fees = TripleFees {
        atom_deposit_fraction: U256::from(150u64),
    };

    let quote =
        preview_triple_deposit(&curve, amount, state, fees, triple_fees, true, true).unwrap();
    assert_eq!(quote.fees.protocol_fee, protocol);
    assert_eq!(quote.fees.entry_fee, entry);
    assert_eq!(quote.fees.atom_deposit_fraction, atom_fraction);
    assert_eq!(
        quote.assets_after_fees,
        amount - protocol - entry - atom_fraction,
        "net assets"
    );
}

// =====================================================================
// Redeem fee simulation — protocol + exit
// =====================================================================

#[test]
fn redeem_fees_match_solidity() {
    let all = fixtures();
    let f = &all["fees"];
    let denom = U256::from(10_000u64);
    let amount = U256::from(10u64) * one();

    let protocol = fee_on_raw(amount, U256::from(100u64), denom).unwrap();
    let exit = fee_on_raw(amount, U256::from(25u64), denom).unwrap();

    assert_eq!(protocol, val(f, "redeem_10e18_protocol"), "protocol");
    assert_eq!(exit, val(f, "redeem_10e18_exit"), "exit");

    // Verify combined
    let curve = LinearCurve::new();
    let state = CurveState {
        total_assets: U256::from(100u64) * one(),
        total_shares: U256::from(100u64) * one(),
    };
    let fees = FeeSchedule {
        denominator: denom,
        protocol_fee: U256::from(100u64),
        entry_fee: U256::from(50u64),
        exit_fee: U256::from(25u64),
    };

    let quote =
        preview_redeem_with_fees(&curve, U256::from(10u64) * one(), state, fees, true).unwrap();
    assert_eq!(quote.fees.protocol_fee, protocol);
    assert_eq!(quote.fees.exit_fee, exit);
    assert_eq!(
        quote.assets_after_fees,
        amount - protocol - exit,
        "net assets"
    );
}
