//! Exhaustive sweep parity: 263 test vectors generated by the real Solidity
//! contracts, covering every method × many input combinations (1 wei → 1M ETH).
//!
//! Fixture: `tests/fixtures/onchain_sweep.json`
//! Generated by: `contracts/core/tests/unit/curves/GenerateSweepFixtures.t.sol`
//!
//! Regenerate:
//!   cd contracts/core && FOUNDRY_PROFILE=test forge test --mt test_generateSweep -vv

use std::{collections::HashMap, fs, path::PathBuf, str::FromStr};

use curves::{Curve, CurveState, LinearCurve, OffsetProgressiveCurve, U256};

type Section = HashMap<String, serde_json::Value>;
type Obj = serde_json::Map<String, serde_json::Value>;

fn load_sweep() -> HashMap<String, Section> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/onchain_sweep.json");
    serde_json::from_str(&fs::read_to_string(path).expect("sweep fixture should exist"))
        .expect("sweep json should deserialize")
}

fn p(v: &serde_json::Value) -> U256 {
    U256::from_str(v.as_str().expect("expected string")).expect("expected U256")
}

fn count(section: &Section) -> usize {
    section["count"].as_str().unwrap().parse::<usize>().unwrap()
}

fn entry<'a>(section: &'a Section, prefix: &str, idx: usize) -> &'a Obj {
    let key = format!("{}_{}", prefix, idx);
    section[&key].as_object().unwrap()
}

// =====================================================================
// Linear curve sweeps
// =====================================================================

#[test]
fn linear_deposit_sweep() {
    let all = load_sweep();
    let sec = &all["linear_deposit"];
    let n = count(sec);
    let curve = LinearCurve::new();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "d", i);
        let amount = p(&e["amount"]);
        let total_assets = p(&e["totalAssets"]);
        let total_shares = p(&e["totalShares"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets,
            total_shares,
        };
        let got = curve.preview_deposit(amount, state).unwrap();
        assert_eq!(
            got, expected,
            "linear deposit #{i}: amount={amount} state=({total_assets},{total_shares})"
        );
        checked += 1;
    }
    assert!(
        checked >= 30,
        "expected ≥30 linear deposit vectors, got {checked}"
    );
}

#[test]
fn linear_redeem_sweep() {
    let all = load_sweep();
    let sec = &all["linear_redeem"];
    let n = count(sec);
    let curve = LinearCurve::new();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "r", i);
        let shares = p(&e["shares"]);
        let total_shares = p(&e["totalShares"]);
        let total_assets = p(&e["totalAssets"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets,
            total_shares,
        };
        let got = curve.preview_redeem(shares, state).unwrap();
        assert_eq!(
            got, expected,
            "linear redeem #{i}: shares={shares} state=({total_assets},{total_shares})"
        );
        checked += 1;
    }
    assert!(
        checked >= 20,
        "expected ≥20 linear redeem vectors, got {checked}"
    );
}

#[test]
fn linear_convert_sweep() {
    let all = load_sweep();
    let sec = &all["linear_convert"];
    let n = count(sec);
    let curve = LinearCurve::new();
    let mut checked = 0;

    for i in 0..n {
        let raw_key_cs = format!("cs_{i}");
        let raw_key_ca = format!("ca_{i}");

        if let Some(obj) = sec.get(&raw_key_cs).and_then(|v| v.as_object()) {
            let assets = p(&obj["assets"]);
            let total_assets = p(&obj["totalAssets"]);
            let total_shares = p(&obj["totalShares"]);
            let expected = p(&obj["result"]);

            let state = CurveState {
                total_assets,
                total_shares,
            };
            let got = curve.convert_to_shares(assets, state).unwrap();
            assert_eq!(got, expected, "linear convertToShares #{i}");
            checked += 1;
        }

        if let Some(obj) = sec.get(&raw_key_ca).and_then(|v| v.as_object()) {
            let shares = p(&obj["shares"]);
            let total_shares = p(&obj["totalShares"]);
            let total_assets = p(&obj["totalAssets"]);
            let expected = p(&obj["result"]);

            let state = CurveState {
                total_assets,
                total_shares,
            };
            let got = curve.convert_to_assets(shares, state).unwrap();
            assert_eq!(got, expected, "linear convertToAssets #{i}");
            checked += 1;
        }
    }
    assert!(
        checked >= 50,
        "expected ≥50 linear convert vectors, got {checked}"
    );
}

// =====================================================================
// Progressive curve sweeps
// =====================================================================

fn prog_curve() -> OffsetProgressiveCurve {
    OffsetProgressiveCurve::new(
        U256::from(2_000_000_000_000_000_000u128),
        U256::from(500_000_000_000_000_000u128),
    )
    .unwrap()
}

#[test]
fn progressive_deposit_sweep() {
    let all = load_sweep();
    let sec = &all["prog_deposit"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "pd", i);
        let amount = p(&e["amount"]);
        let total_assets = p(&e["totalAssets"]);
        let total_shares = p(&e["totalShares"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets,
            total_shares,
        };
        let got = curve.preview_deposit(amount, state).unwrap();
        assert_eq!(
            got, expected,
            "prog deposit #{i}: amount={amount} shares={total_shares}"
        );
        checked += 1;
    }
    assert!(
        checked >= 30,
        "expected ≥30 prog deposit vectors, got {checked}"
    );
}

#[test]
fn progressive_redeem_sweep() {
    let all = load_sweep();
    let sec = &all["prog_redeem"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "pr", i);
        let shares = p(&e["shares"]);
        let total_shares = p(&e["totalShares"]);
        let total_assets = p(&e["totalAssets"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets,
            total_shares,
        };
        let got = curve.preview_redeem(shares, state).unwrap();
        assert_eq!(
            got, expected,
            "prog redeem #{i}: shares={shares} total={total_shares}"
        );
        checked += 1;
    }
    assert!(
        checked >= 15,
        "expected ≥15 prog redeem vectors, got {checked}"
    );
}

#[test]
fn progressive_mint_sweep() {
    let all = load_sweep();
    let sec = &all["prog_mint"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "pm", i);
        let shares = p(&e["shares"]);
        let total_shares = p(&e["totalShares"]);
        let total_assets = p(&e["totalAssets"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets,
            total_shares,
        };
        let got = curve.preview_mint(shares, state).unwrap();
        assert_eq!(
            got, expected,
            "prog mint #{i}: shares={shares} total={total_shares}"
        );
        checked += 1;
    }
    assert!(
        checked >= 15,
        "expected ≥15 prog mint vectors, got {checked}"
    );
}

#[test]
fn progressive_withdraw_sweep() {
    let all = load_sweep();
    let sec = &all["prog_withdraw"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "pw", i);
        let assets = p(&e["assets"]);
        let total_assets = p(&e["totalAssets"]);
        let total_shares = p(&e["totalShares"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets,
            total_shares,
        };
        let got = curve.preview_withdraw(assets, state).unwrap();
        assert_eq!(
            got, expected,
            "prog withdraw #{i}: assets={assets} total_shares={total_shares}"
        );
        checked += 1;
    }
    assert!(
        checked >= 10,
        "expected ≥10 prog withdraw vectors, got {checked}"
    );
}

#[test]
fn progressive_price_sweep() {
    let all = load_sweep();
    let sec = &all["prog_price"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "pp", i);
        let total_shares = p(&e["totalShares"]);
        let expected = p(&e["result"]);

        let state = CurveState {
            total_assets: U256::ZERO,
            total_shares,
        };
        let got = curve.current_price(state).unwrap();
        assert_eq!(got, expected, "prog price #{i}: shares={total_shares}");
        checked += 1;
    }
    assert!(
        checked >= 5,
        "expected ≥5 prog price vectors, got {checked}"
    );
}

#[test]
fn progressive_convert_sweep() {
    let all = load_sweep();
    let sec = &all["prog_convert"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let raw_key_cs = format!("pcs_{i}");
        let raw_key_ca = format!("pca_{i}");

        if let Some(obj) = sec.get(&raw_key_cs).and_then(|v| v.as_object()) {
            let assets = p(&obj["assets"]);
            let total_assets = p(&obj["totalAssets"]);
            let total_shares = p(&obj["totalShares"]);
            let expected = p(&obj["result"]);

            let state = CurveState {
                total_assets,
                total_shares,
            };
            let got = curve.convert_to_shares(assets, state).unwrap();
            assert_eq!(got, expected, "prog convertToShares #{i}");
            checked += 1;
        }

        if let Some(obj) = sec.get(&raw_key_ca).and_then(|v| v.as_object()) {
            let shares = p(&obj["shares"]);
            let total_shares = p(&obj["totalShares"]);
            let total_assets = p(&obj["totalAssets"]);
            let expected = p(&obj["result"]);

            let state = CurveState {
                total_assets,
                total_shares,
            };
            let got = curve.convert_to_assets(shares, state).unwrap();
            assert_eq!(got, expected, "prog convertToAssets #{i}");
            checked += 1;
        }
    }
    assert!(
        checked >= 25,
        "expected ≥25 prog convert vectors, got {checked}"
    );
}

// =====================================================================
// Round-trip cross-method: deposit→redeem verified against Solidity
// =====================================================================

#[test]
fn round_trip_sweep() {
    let all = load_sweep();
    let sec = &all["round_trips"];
    let n = count(sec);
    let curve = prog_curve();
    let mut checked = 0;

    for i in 0..n {
        let e = entry(sec, "rt", i);
        let deposited = p(&e["deposited"]);
        let total_shares_before = p(&e["totalSharesBefore"]);
        let expected_shares = p(&e["sharesReceived"]);
        let expected_assets_back = p(&e["assetsReturned"]);
        let expected_loss = p(&e["loss"]);

        // Step 1: deposit
        let state_before = CurveState {
            total_assets: U256::ZERO,
            total_shares: total_shares_before,
        };
        let shares = curve.preview_deposit(deposited, state_before).unwrap();
        assert_eq!(
            shares, expected_shares,
            "round-trip #{i} deposit shares mismatch"
        );

        // Step 2: redeem
        let state_after = CurveState {
            total_assets: deposited,
            total_shares: total_shares_before + shares,
        };
        let assets_back = curve.preview_redeem(shares, state_after).unwrap();
        assert_eq!(
            assets_back, expected_assets_back,
            "round-trip #{i} redeem assets mismatch"
        );

        // Step 3: verify loss matches Solidity
        let loss = deposited - assets_back;
        assert_eq!(loss, expected_loss, "round-trip #{i} loss mismatch");

        // Protocol invariant: never profit from round-trip
        assert!(assets_back <= deposited, "round-trip #{i} profit detected");
        checked += 1;
    }
    assert!(
        checked >= 10,
        "expected ≥10 round-trip vectors, got {checked}"
    );
}
