/**
 * Workflow Artifact Types and Utilities
 *
 * This module exports comprehensive types and utilities for working with
 * AI workflow results and artifacts across the Intuition monorepo.
 *
 * @module @0xintuition/types/workflows
 *
 * @example
 * ```typescript
 * import {
 *   type WorkflowResult,
 *   type AtomData,
 *   extractAtomData,
 *   isWorkflowCompleted,
 * } from '@0xintuition/types/workflows';
 *
 * function processWorkflow(result: WorkflowResult) {
 *   if (isWorkflowCompleted(result)) {
 *     const atom = extractAtomData(result);
 *     console.log(atom?.name);
 *   }
 * }
 * ```
 */

// Core Types
export type {
	AdPrompt,
	Advertisement,
	AestheticStyle,
	AmazonProductData,
	Artifact,
	ArtifactDataByType,
	ArtifactType,
	AspectRatio,
	AtomData,
	AtomDataInput,
	BuyingStyle,
	ContentResponsiveness,
	CustomerSegment,
	EnrichedAtomData,
	EnvironmentType,
	FashionSensibility,
	ImageCategories,
	ImagePrompt,
	ImagePromptCode,
	ImageSize,
	IncomeLevel,
	Lifestage,
	LivingContext,
	MarketAnalysisData,
	MarketAnalysisOverview,
	MarketAnalysisResult,
	PriceMotivation,
	PrimaryValue,
	ProductData,
	ProductDataInput,
	ProductImageCategories,
	Sex,
	SocialPlatform,
	StepOutputStatus,
	TargetMarketSegment,
	TonePreference,
	TypedWorkflowResult,
	UGCArchetype,
	WorkflowClassification,
	WorkflowError,
	WorkflowMetadata,
	WorkflowResult,
	WorkflowStatus,
	WorkflowStepResult,
} from './types';
// Core Schemas
export {
	AdPromptSchema,
	AdvertisementSchema,
	AestheticStyleSchema,
	AmazonProductDataSchema,
	ArtifactTypeSchema,
	AspectRatioSchema,
	AtomDataInputSchema,
	AtomDataSchema,
	BuyingStyleSchema,
	ContentResponsivenessSchema,
	CustomerSegmentSchema,
	EnrichedAtomDataSchema,
	EnvironmentTypeSchema,
	FashionSensibilitySchema,
	ImageCategoriesSchema,
	ImagePromptCodeSchema,
	ImagePromptSchema,
	ImagePromptsSchema,
	ImageSizeSchema,
	IncomeLevelSchema,
	LifestageSchema,
	LivingContextSchema,
	MarketAnalysisDataSchema,
	MarketAnalysisOverviewSchema,
	MarketAnalysisResultSchema,
	PriceMotivationSchema,
	PrimaryValuesSchema,
	ProductDataInputSchema,
	ProductDataSchema,
	ProductImageCategoriesSchema,
	SexSchema,
	SocialPlatformSchema,
	StepOutputStatusSchema,
	TargetMarketSegmentSchema,
	TonePreferenceSchema,
	UGCArchetypeSchema,
	WorkflowClassificationSchema,
	WorkflowErrorSchema,
	WorkflowMetadataSchema,
	WorkflowResultSchema,
	WorkflowStatusSchema,
	WorkflowStepResultSchema,
} from './types';
// Utilities
export {
	classificationToArtifactType,
	extractAdvertisements,
	extractAtomData,
	extractCustomerSegments,
	extractFileUrls,
	extractImagePrompts,
	extractMarketAnalysis,
	extractProductData,
	extractWorkflowError,
	extractWorkflowOutputResult,
	extractWorkflowResult,
	formatDuration,
	getClassificationLabel,
	getInputFileUrls,
	getStatusLabel,
	getWorkflowCompletedAt,
	getWorkflowDuration,
	getWorkflowErrorMessage,
	getWorkflowStartedAt,
	getWorkflowStep,
	getWorkflowSteps,
	hasAtomInput,
	hasFileUrls,
	hasProductInput,
	isAdvertisement,
	isAtomData,
	isCustomerSegment,
	isImagePrompt,
	isMarketAnalysisData,
	isProductData,
	isStepCompleted,
	isWorkflowClassification,
	isWorkflowCompleted,
	isWorkflowFailed,
	isWorkflowRunning,
	isWorkflowStatus,
	parseAdvertisement,
	parseAtomData,
	parseCustomerSegment,
	parseImagePrompt,
	parseMarketAnalysisData,
	parseProductData,
	parseWorkflowResult,
} from './utils';
