export type {
	AiClassificationSuggestion,
	AiPluginAdapter,
	OptionalAiFallbackPluginOptions,
} from './ai';
export { createOptionalAiFallbackPlugin } from './ai';
export type {
	ClassificationCacheAdapter,
	ClassificationResolverCachedEntry,
} from './cache';
export {
	buildClassificationResolverCacheKey,
	createMemoryClassificationCacheAdapter,
	createUpstashClassificationCacheAdapter,
	createUpstashClassificationCacheAdapterFromEnv,
	isClassificationResolverCachedEntryFresh,
} from './cache';
export type { CreateClientEngineOptions } from './client';
export { createClientEngine } from './client';
export type {
	ClassificationEngine,
	ClassificationEngineInitResult,
	ClassificationRuntime,
	CreateClassificationEngineOptions,
} from './engine';
export { createClassificationEngine } from './engine';
export type {
	AtomClassificationPlugin,
	AtomClassifier,
	AtomResolver,
	HookContext,
	HookExecutionError,
	HookHandlers,
	HookPatch,
	HookStage,
	PluginManifest,
	PluginSecurityViolation,
	ResolverAtom,
	ResolverClassification,
	ResolverContext,
	ResolverExecutionMode,
	ResolverResult,
	RuntimeTarget,
} from './plugins';
export {
	ENGINE_VERSION,
	getPluginSecurityViolations,
	isEngineVersionCompatible,
	isRuntimeCompatible,
	pluginManifestSchema,
	resolverExecutionModeSchema,
	runtimeTargetSchema,
	validatePluginManifest,
} from './plugins';
export {
	type AmazonCanopyPluginOptionsInput,
	type AmazonDomainApiAdapter,
	type AmazonDomainApiAdapterOptions,
	type AmazonDomainHtmlAdapter,
	type AmazonDomainHtmlAdapterOptions,
	type AmazonPluginOptions,
	createAmazonCanopyPluginOptions,
	createAmazonDomainApiAdapter,
	createAmazonDomainHtmlAdapter,
	createAmazonPlugin,
	createDefaultUrlPlugin,
	createEthereumPlugin,
	createEtherscanPlugin,
	createGitHubDomainApiAdapter,
	createGitHubPlugin,
	createImdbDomainHtmlAdapter,
	createImdbPlugin,
	createInstagramPlugin,
	createIsbnPlugin,
	createLexicalPlugin,
	createNonUrlV0Profiles,
	createNpmPlugin,
	createOpenGraphPlatformAdapter,
	createPlainTextPlugin,
	createPlatformV0Profiles,
	createPublicMetadataPlatformAdapter,
	createSpotifyDomainApiAdapter,
	createSpotifyPlugin,
	createTikTokPlugin,
	createTmdbPlugin,
	createTypeProfilesPlugin,
	createV0TypeProfilesPlugin,
	createWikipediaPlugin,
	createXDomainApiAdapter,
	createXOpenGraphAdapter,
	createXPlugin,
	createXPublicMetadataAdapter,
	createYouTubeOEmbedAdapter,
	createYouTubePlugin,
	type EtherscanPluginOptions,
	type GitHubDomainApiAdapter,
	type GitHubDomainApiAdapterOptions,
	type GitHubPluginOptions,
	type ImdbDomainHtmlAdapter,
	type ImdbDomainHtmlAdapterOptions,
	type ImdbPluginOptions,
	type InstagramPluginOptions,
	type NonUrlV0Profile,
	type NpmPluginOptions,
	type OpenGraphMetadata,
	type OpenGraphPlatformAdapter,
	type OpenGraphPlatformAdapterInput,
	type OpenGraphPlatformAdapterOptions,
	type PlatformDomain,
	type PlatformV0PluginOptions,
	type PlatformV0Profile,
	type PublicMetadataPlatformAdapter,
	type PublicMetadataPlatformAdapterOptions,
	type PublicMetadataSource,
	type PublicMetadataSourceResult,
	type SpotifyDomainApiAdapter,
	type SpotifyDomainApiAdapterOptions,
	type SpotifyPluginOptions,
	type TikTokPluginOptions,
	type TmdbPluginOptions,
	type WikipediaPluginOptions,
	type XDomainApiAdapter,
	type XDomainApiAdapterOptions,
	type XEnrichmentAdapter,
	type XEnrichmentAdapterInput,
	type XEnrichmentPayload,
	type XOpenGraphAdapter,
	type XOpenGraphAdapterOptions,
	type XPluginOptions,
	type XPublicMetadataAdapter,
	type XPublicMetadataAdapterOptions,
	type XResolutionMode,
	type YouTubeOEmbedAdapter,
	type YouTubeOEmbedAdapterOptions,
	type YouTubePluginOptions,
} from './plugins/index';
export type { DefaultClassificationPresetOptions } from './presets';
export { defaultClassificationPreset } from './presets';
export type { CreateServerEngineOptions } from './server';
export { createServerEngine } from './server';
export type {
	JsonLdTypeCategory,
	JsonLdTypeDefinition,
	JsonLdTypeRegistry,
	RegisterTypeOptions,
} from './type-registry';
export {
	createJsonLdTypeRegistry,
	jsonLdTypeCategorySchema,
	jsonLdTypeDefinitionSchema,
	registerTypeOptionsSchema,
	validateJsonLdTypeDefinition,
	validateRegisterTypeOptions,
} from './type-registry';
export type {
	ClassificationCanonicalData,
	ClassificationCanonicalEnvelope,
	ClassificationCanonicalFieldPolicy,
	ClassificationCanonicalFieldPolicyMap,
	ClassificationCanonicalMeta,
	ClassificationClientClassificationHint,
	ClassificationClientHints,
	ClassificationEntityCategory,
	ClassificationFieldProvenanceEntry,
	ClassificationFieldProvenanceMap,
	ClassificationInputIntent,
	ClassificationMode,
	ClassificationPluginId,
	ClassificationPromotionTier,
	ClassificationRequest,
	ClassificationRequestInput,
	ClassificationResolvedAtom,
	ClassificationResolvedPayload,
	ClassificationResolverError,
	ClassificationResult,
	ClassificationServerTier,
	ClassificationSourceFamily,
	EnhancementPolicy,
	EnhancementPolicyOverride,
} from './types';
export {
	classificationCanonicalDataSchema,
	classificationCanonicalEnvelopeSchema,
	classificationCanonicalFieldPolicyMapSchema,
	classificationCanonicalFieldPolicySchema,
	classificationCanonicalMetaSchema,
	classificationClientClassificationHintSchema,
	classificationClientHintsSchema,
	classificationClientResultHintSchema,
	classificationEntityCategorySchema,
	classificationFieldProvenanceEntrySchema,
	classificationFieldProvenanceMapSchema,
	classificationInputIntentSchema,
	classificationInputTypeSchema,
	classificationModeSchema,
	classificationPluginIdSchema,
	classificationPromotionTierSchema,
	classificationProvenanceSourceSchema,
	classificationRequestSchema,
	classificationResolvedAtomSchema,
	classificationResolvedPayloadSchema,
	classificationResolverErrorSchema,
	classificationResultSchema,
	classificationRuntimeSchema,
	classificationServerTierSchema,
	classificationSessionIdSchema,
	classificationSourceFamilySchema,
	enhancementPolicyOverrideSchema,
	enhancementPolicySchema,
	getDefaultEnhancementPolicy,
	resolveEnhancementPolicy,
} from './types';
