/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as PredicatesRouteImport } from './routes/predicates'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TriplesIndexRouteImport } from './routes/triples.index'
import { Route as AtomsIndexRouteImport } from './routes/atoms.index'
import { Route as TriplesTripleIdRouteImport } from './routes/triples.$tripleId'
import { Route as AtomsAtomIdRouteImport } from './routes/atoms.$atomId'
import { Route as ApiStatusRouteImport } from './routes/api/status'

const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const PredicatesRoute = PredicatesRouteImport.update({
  id: '/predicates',
  path: '/predicates',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriplesIndexRoute = TriplesIndexRouteImport.update({
  id: '/triples/',
  path: '/triples/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomsIndexRoute = AtomsIndexRouteImport.update({
  id: '/atoms/',
  path: '/atoms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriplesTripleIdRoute = TriplesTripleIdRouteImport.update({
  id: '/triples/$tripleId',
  path: '/triples/$tripleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomsAtomIdRoute = AtomsAtomIdRouteImport.update({
  id: '/atoms/$atomId',
  path: '/atoms/$atomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/playground': typeof PlaygroundRoute
  '/predicates': typeof PredicatesRoute
  '/schema': typeof SchemaRoute
  '/api/status': typeof ApiStatusRoute
  '/atoms/$atomId': typeof AtomsAtomIdRoute
  '/triples/$tripleId': typeof TriplesTripleIdRoute
  '/atoms/': typeof AtomsIndexRoute
  '/triples/': typeof TriplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/playground': typeof PlaygroundRoute
  '/predicates': typeof PredicatesRoute
  '/schema': typeof SchemaRoute
  '/api/status': typeof ApiStatusRoute
  '/atoms/$atomId': typeof AtomsAtomIdRoute
  '/triples/$tripleId': typeof TriplesTripleIdRoute
  '/atoms': typeof AtomsIndexRoute
  '/triples': typeof TriplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/playground': typeof PlaygroundRoute
  '/predicates': typeof PredicatesRoute
  '/schema': typeof SchemaRoute
  '/api/status': typeof ApiStatusRoute
  '/atoms/$atomId': typeof AtomsAtomIdRoute
  '/triples/$tripleId': typeof TriplesTripleIdRoute
  '/atoms/': typeof AtomsIndexRoute
  '/triples/': typeof TriplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/playground'
    | '/predicates'
    | '/schema'
    | '/api/status'
    | '/atoms/$atomId'
    | '/triples/$tripleId'
    | '/atoms/'
    | '/triples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/playground'
    | '/predicates'
    | '/schema'
    | '/api/status'
    | '/atoms/$atomId'
    | '/triples/$tripleId'
    | '/atoms'
    | '/triples'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/playground'
    | '/predicates'
    | '/schema'
    | '/api/status'
    | '/atoms/$atomId'
    | '/triples/$tripleId'
    | '/atoms/'
    | '/triples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PredicatesRoute: typeof PredicatesRoute
  SchemaRoute: typeof SchemaRoute
  ApiStatusRoute: typeof ApiStatusRoute
  AtomsAtomIdRoute: typeof AtomsAtomIdRoute
  TriplesTripleIdRoute: typeof TriplesTripleIdRoute
  AtomsIndexRoute: typeof AtomsIndexRoute
  TriplesIndexRoute: typeof TriplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predicates': {
      id: '/predicates'
      path: '/predicates'
      fullPath: '/predicates'
      preLoaderRoute: typeof PredicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triples/': {
      id: '/triples/'
      path: '/triples'
      fullPath: '/triples/'
      preLoaderRoute: typeof TriplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atoms/': {
      id: '/atoms/'
      path: '/atoms'
      fullPath: '/atoms/'
      preLoaderRoute: typeof AtomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triples/$tripleId': {
      id: '/triples/$tripleId'
      path: '/triples/$tripleId'
      fullPath: '/triples/$tripleId'
      preLoaderRoute: typeof TriplesTripleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atoms/$atomId': {
      id: '/atoms/$atomId'
      path: '/atoms/$atomId'
      fullPath: '/atoms/$atomId'
      preLoaderRoute: typeof AtomsAtomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PredicatesRoute: PredicatesRoute,
  SchemaRoute: SchemaRoute,
  ApiStatusRoute: ApiStatusRoute,
  AtomsAtomIdRoute: AtomsAtomIdRoute,
  TriplesTripleIdRoute: TriplesTripleIdRoute,
  AtomsIndexRoute: AtomsIndexRoute,
  TriplesIndexRoute: TriplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
