#![allow(
    non_camel_case_types,
    clippy::enum_variant_names,
    clippy::too_many_arguments,
    clippy::upper_case_acronyms,
    clippy::type_complexity,
    dead_code
)]
use super::super::super::super::typings::networks::get_provider_cache_for_network;
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
/// Any manual changes to this file will be overwritten.
use super::multi_vault_abi_gen::RindexerMultiVaultGen::{
    self, RindexerMultiVaultGenEvents, RindexerMultiVaultGenInstance,
};
use alloy::network::AnyNetwork;
use alloy::primitives::{Address, Bytes, B256};
use alloy::sol_types::{SolEvent, SolEventInterface, SolType};
use rindexer::{
    async_trait,
    blockclock::BlockClock,
    event::{
        callback_registry::{
            EventCallbackRegistry, EventCallbackRegistryInformation, EventCallbackResult,
            EventResult, HasTxInformation, TxInformation,
        },
        contract_setup::{ContractInformation, NetworkContract},
    },
    generate_random_id,
    manifest::{
        contract::{Contract, ContractDetails},
        yaml::read_manifest,
    },
    provider::{JsonRpcCachedProvider, RindexerProvider},
    FutureExt,
};
use std::collections::HashMap;
use std::error::Error;
use std::future::Future;
use std::path::{Path, PathBuf};
use std::pin::Pin;
use std::{any::Any, sync::Arc};

pub type ApprovalTypeUpdatedData = RindexerMultiVaultGen::ApprovalTypeUpdated;

#[derive(Debug, Clone)]
pub struct ApprovalTypeUpdatedResult {
    pub event_data: ApprovalTypeUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for ApprovalTypeUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type AtomConfigUpdatedData = RindexerMultiVaultGen::AtomConfigUpdated;

#[derive(Debug, Clone)]
pub struct AtomConfigUpdatedResult {
    pub event_data: AtomConfigUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for AtomConfigUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type AtomCreatedData = RindexerMultiVaultGen::AtomCreated;

#[derive(Debug, Clone)]
pub struct AtomCreatedResult {
    pub event_data: AtomCreatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for AtomCreatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type AtomWalletDepositFeeCollectedData = RindexerMultiVaultGen::AtomWalletDepositFeeCollected;

#[derive(Debug, Clone)]
pub struct AtomWalletDepositFeeCollectedResult {
    pub event_data: AtomWalletDepositFeeCollectedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for AtomWalletDepositFeeCollectedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type AtomWalletDepositFeesClaimedData = RindexerMultiVaultGen::AtomWalletDepositFeesClaimed;

#[derive(Debug, Clone)]
pub struct AtomWalletDepositFeesClaimedResult {
    pub event_data: AtomWalletDepositFeesClaimedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for AtomWalletDepositFeesClaimedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type BondingCurveConfigUpdatedData = RindexerMultiVaultGen::BondingCurveConfigUpdated;

#[derive(Debug, Clone)]
pub struct BondingCurveConfigUpdatedResult {
    pub event_data: BondingCurveConfigUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for BondingCurveConfigUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type DepositedData = RindexerMultiVaultGen::Deposited;

#[derive(Debug, Clone)]
pub struct DepositedResult {
    pub event_data: DepositedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for DepositedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type GeneralConfigUpdatedData = RindexerMultiVaultGen::GeneralConfigUpdated;

#[derive(Debug, Clone)]
pub struct GeneralConfigUpdatedResult {
    pub event_data: GeneralConfigUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for GeneralConfigUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type InitializedData = RindexerMultiVaultGen::Initialized;

#[derive(Debug, Clone)]
pub struct InitializedResult {
    pub event_data: InitializedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for InitializedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type PausedData = RindexerMultiVaultGen::Paused;

#[derive(Debug, Clone)]
pub struct PausedResult {
    pub event_data: PausedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for PausedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type PersonalUtilizationAddedData = RindexerMultiVaultGen::PersonalUtilizationAdded;

#[derive(Debug, Clone)]
pub struct PersonalUtilizationAddedResult {
    pub event_data: PersonalUtilizationAddedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for PersonalUtilizationAddedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type PersonalUtilizationRemovedData = RindexerMultiVaultGen::PersonalUtilizationRemoved;

#[derive(Debug, Clone)]
pub struct PersonalUtilizationRemovedResult {
    pub event_data: PersonalUtilizationRemovedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for PersonalUtilizationRemovedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type ProtocolFeeAccruedData = RindexerMultiVaultGen::ProtocolFeeAccrued;

#[derive(Debug, Clone)]
pub struct ProtocolFeeAccruedResult {
    pub event_data: ProtocolFeeAccruedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for ProtocolFeeAccruedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type ProtocolFeeTransferredData = RindexerMultiVaultGen::ProtocolFeeTransferred;

#[derive(Debug, Clone)]
pub struct ProtocolFeeTransferredResult {
    pub event_data: ProtocolFeeTransferredData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for ProtocolFeeTransferredResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type RedeemedData = RindexerMultiVaultGen::Redeemed;

#[derive(Debug, Clone)]
pub struct RedeemedResult {
    pub event_data: RedeemedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for RedeemedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type RoleAdminChangedData = RindexerMultiVaultGen::RoleAdminChanged;

#[derive(Debug, Clone)]
pub struct RoleAdminChangedResult {
    pub event_data: RoleAdminChangedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for RoleAdminChangedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type RoleGrantedData = RindexerMultiVaultGen::RoleGranted;

#[derive(Debug, Clone)]
pub struct RoleGrantedResult {
    pub event_data: RoleGrantedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for RoleGrantedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type RoleRevokedData = RindexerMultiVaultGen::RoleRevoked;

#[derive(Debug, Clone)]
pub struct RoleRevokedResult {
    pub event_data: RoleRevokedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for RoleRevokedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type SharePriceChangedData = RindexerMultiVaultGen::SharePriceChanged;

#[derive(Debug, Clone)]
pub struct SharePriceChangedResult {
    pub event_data: SharePriceChangedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for SharePriceChangedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type TotalUtilizationAddedData = RindexerMultiVaultGen::TotalUtilizationAdded;

#[derive(Debug, Clone)]
pub struct TotalUtilizationAddedResult {
    pub event_data: TotalUtilizationAddedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for TotalUtilizationAddedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type TotalUtilizationRemovedData = RindexerMultiVaultGen::TotalUtilizationRemoved;

#[derive(Debug, Clone)]
pub struct TotalUtilizationRemovedResult {
    pub event_data: TotalUtilizationRemovedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for TotalUtilizationRemovedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type TripleConfigUpdatedData = RindexerMultiVaultGen::TripleConfigUpdated;

#[derive(Debug, Clone)]
pub struct TripleConfigUpdatedResult {
    pub event_data: TripleConfigUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for TripleConfigUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type TripleCreatedData = RindexerMultiVaultGen::TripleCreated;

#[derive(Debug, Clone)]
pub struct TripleCreatedResult {
    pub event_data: TripleCreatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for TripleCreatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type UnpausedData = RindexerMultiVaultGen::Unpaused;

#[derive(Debug, Clone)]
pub struct UnpausedResult {
    pub event_data: UnpausedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for UnpausedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type VaultFeesUpdatedData = RindexerMultiVaultGen::VaultFeesUpdated;

#[derive(Debug, Clone)]
pub struct VaultFeesUpdatedResult {
    pub event_data: VaultFeesUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for VaultFeesUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

pub type WalletConfigUpdatedData = RindexerMultiVaultGen::WalletConfigUpdated;

#[derive(Debug, Clone)]
pub struct WalletConfigUpdatedResult {
    pub event_data: WalletConfigUpdatedData,
    pub tx_information: TxInformation,
}

impl HasTxInformation for WalletConfigUpdatedResult {
    fn tx_information(&self) -> &TxInformation {
        &self.tx_information
    }
}

type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

#[async_trait]
trait EventCallback {
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()>;
}

pub struct EventContext<TExtensions>
where
    TExtensions: Send + Sync,
{
    pub extensions: Arc<TExtensions>,
}

// didn't want to use option or none made harder DX
// so a blank struct makes interface nice
pub struct NoExtensions {}
pub fn no_extensions() -> NoExtensions {
    NoExtensions {}
}

pub fn atomcreated_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> AtomCreatedEventCallbackType<TExtensions>
where
    AtomCreatedResult: Clone + 'static,
    F: for<'a> Fn(Vec<AtomCreatedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type AtomCreatedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<AtomCreatedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct AtomCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: AtomCreatedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> AtomCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        AtomCreatedResult: Clone + 'static,
        F: for<'a> Fn(Vec<AtomCreatedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        Self {
            callback: atomcreated_handler(closure),
            context: Arc::new(EventContext {
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for AtomCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<AtomCreatedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data
                    .downcast::<AtomCreatedData>()
                    .ok()
                    .map(|arc| AtomCreatedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("AtomCreatedEvent: Unexpected data type - expected: AtomCreatedData")
        }
    }
}

pub fn deposited_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> DepositedEventCallbackType<TExtensions>
where
    DepositedResult: Clone + 'static,
    F: for<'a> Fn(Vec<DepositedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type DepositedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<DepositedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct DepositedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: DepositedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> DepositedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        DepositedResult: Clone + 'static,
        F: for<'a> Fn(Vec<DepositedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        Self {
            callback: deposited_handler(closure),
            context: Arc::new(EventContext {
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for DepositedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<DepositedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data
                    .downcast::<DepositedData>()
                    .ok()
                    .map(|arc| DepositedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("DepositedEvent: Unexpected data type - expected: DepositedData")
        }
    }
}

pub fn protocolfeeaccrued_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> ProtocolFeeAccruedEventCallbackType<TExtensions>
where
    ProtocolFeeAccruedResult: Clone + 'static,
    F: for<'a> Fn(Vec<ProtocolFeeAccruedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type ProtocolFeeAccruedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<ProtocolFeeAccruedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct ProtocolFeeAccruedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: ProtocolFeeAccruedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> ProtocolFeeAccruedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        ProtocolFeeAccruedResult: Clone + 'static,
        F: for<'a> Fn(Vec<ProtocolFeeAccruedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        Self {
            callback: protocolfeeaccrued_handler(closure),
            context: Arc::new(EventContext {
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for ProtocolFeeAccruedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<ProtocolFeeAccruedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data
                    .downcast::<ProtocolFeeAccruedData>()
                    .ok()
                    .map(|arc| ProtocolFeeAccruedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!(
                "ProtocolFeeAccruedEvent: Unexpected data type - expected: ProtocolFeeAccruedData"
            )
        }
    }
}

pub fn redeemed_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> RedeemedEventCallbackType<TExtensions>
where
    RedeemedResult: Clone + 'static,
    F: for<'a> Fn(Vec<RedeemedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type RedeemedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<RedeemedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct RedeemedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: RedeemedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> RedeemedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        RedeemedResult: Clone + 'static,
        F: for<'a> Fn(Vec<RedeemedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        Self {
            callback: redeemed_handler(closure),
            context: Arc::new(EventContext {
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for RedeemedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<RedeemedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data
                    .downcast::<RedeemedData>()
                    .ok()
                    .map(|arc| RedeemedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("RedeemedEvent: Unexpected data type - expected: RedeemedData")
        }
    }
}

pub fn sharepricechanged_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> SharePriceChangedEventCallbackType<TExtensions>
where
    SharePriceChangedResult: Clone + 'static,
    F: for<'a> Fn(Vec<SharePriceChangedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type SharePriceChangedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<SharePriceChangedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct SharePriceChangedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: SharePriceChangedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> SharePriceChangedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        SharePriceChangedResult: Clone + 'static,
        F: for<'a> Fn(Vec<SharePriceChangedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        Self {
            callback: sharepricechanged_handler(closure),
            context: Arc::new(EventContext {
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for SharePriceChangedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<SharePriceChangedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data
                    .downcast::<SharePriceChangedData>()
                    .ok()
                    .map(|arc| SharePriceChangedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("SharePriceChangedEvent: Unexpected data type - expected: SharePriceChangedData")
        }
    }
}

pub fn triplecreated_handler<TExtensions, F, Fut>(
    custom_logic: F,
) -> TripleCreatedEventCallbackType<TExtensions>
where
    TripleCreatedResult: Clone + 'static,
    F: for<'a> Fn(Vec<TripleCreatedResult>, Arc<EventContext<TExtensions>>) -> Fut
        + Send
        + Sync
        + 'static
        + Clone,
    Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    TExtensions: Send + Sync + 'static,
{
    Arc::new(move |results, context| {
        let custom_logic = custom_logic.clone();
        let results = results.clone();
        let context = Arc::clone(&context);
        async move { (custom_logic)(results, context).await }.boxed()
    })
}

type TripleCreatedEventCallbackType<TExtensions> = Arc<
    dyn for<'a> Fn(
            &'a Vec<TripleCreatedResult>,
            Arc<EventContext<TExtensions>>,
        ) -> BoxFuture<'a, EventCallbackResult<()>>
        + Send
        + Sync,
>;

pub struct TripleCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    callback: TripleCreatedEventCallbackType<TExtensions>,
    context: Arc<EventContext<TExtensions>>,
}

impl<TExtensions> TripleCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync + 'static,
{
    pub async fn handler<F, Fut>(closure: F, extensions: TExtensions) -> Self
    where
        TripleCreatedResult: Clone + 'static,
        F: for<'a> Fn(Vec<TripleCreatedResult>, Arc<EventContext<TExtensions>>) -> Fut
            + Send
            + Sync
            + 'static
            + Clone,
        Fut: Future<Output = EventCallbackResult<()>> + Send + 'static,
    {
        Self {
            callback: triplecreated_handler(closure),
            context: Arc::new(EventContext {
                extensions: Arc::new(extensions),
            }),
        }
    }
}

#[async_trait]
impl<TExtensions> EventCallback for TripleCreatedEvent<TExtensions>
where
    TExtensions: Send + Sync,
{
    async fn call(&self, events: Vec<EventResult>) -> EventCallbackResult<()> {
        let events_len = events.len();

        // note some can not downcast because it cant decode
        // this happens on events which failed decoding due to
        // not having the right abi for example
        // transfer events with 2 indexed topics cant decode
        // transfer events with 3 indexed topics
        let result: Vec<TripleCreatedResult> = events
            .into_iter()
            .filter_map(|item| {
                item.decoded_data
                    .downcast::<TripleCreatedData>()
                    .ok()
                    .map(|arc| TripleCreatedResult {
                        event_data: (*arc).clone(),
                        tx_information: item.tx_information,
                    })
            })
            .collect();

        if result.len() == events_len {
            (self.callback)(&result, Arc::clone(&self.context)).await
        } else {
            panic!("TripleCreatedEvent: Unexpected data type - expected: TripleCreatedData")
        }
    }
}

pub enum MultiVaultEventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    AtomCreated(AtomCreatedEvent<TExtensions>),
    Deposited(DepositedEvent<TExtensions>),
    ProtocolFeeAccrued(ProtocolFeeAccruedEvent<TExtensions>),
    Redeemed(RedeemedEvent<TExtensions>),
    SharePriceChanged(SharePriceChangedEvent<TExtensions>),
    TripleCreated(TripleCreatedEvent<TExtensions>),
}

pub async fn multi_vault_contract(
    network: &str,
) -> RindexerMultiVaultGenInstance<Arc<RindexerProvider>, AnyNetwork> {
    let address: Address = "0xebc49d356b7f64d888130d85cc6d17114a6843ec"
        .parse()
        .expect("Invalid address");
    RindexerMultiVaultGen::new(
        address,
        get_provider_cache_for_network(network)
            .await
            .get_inner_provider(),
    )
}

pub async fn decoder_contract(
    network: &str,
) -> RindexerMultiVaultGenInstance<Arc<RindexerProvider>, AnyNetwork> {
    if network == "intuition" {
        RindexerMultiVaultGen::new(
            // do not care about address here its decoding makes it easier to handle ValueOrArray
            Address::ZERO,
            get_provider_cache_for_network(network)
                .await
                .get_inner_provider(),
        )
    } else {
        panic!("Network not supported");
    }
}

impl<TExtensions> MultiVaultEventType<TExtensions>
where
    TExtensions: 'static + Send + Sync,
{
    pub fn topic_id(&self) -> &'static str {
        match self {
            MultiVaultEventType::AtomCreated(_) => {
                "0xfd579ad7468b1720e08f84efe16900074f3ffdaaeaa82e675e5aec69bf393189"
            }
            MultiVaultEventType::Deposited(_) => {
                "0xf717428d3271f4ca44ee92a96ecda708463de1c200f30db4e295def5e8db6b4a"
            }
            MultiVaultEventType::ProtocolFeeAccrued(_) => {
                "0xc7a5742f069dec143091f9dc7c9ca18f1212ac3f76cd16f5f8aa6f5cab9b2afc"
            }
            MultiVaultEventType::Redeemed(_) => {
                "0x5ab85658e5658520d47644e1417584159fc8edb9712149792a9337ff5e1048a4"
            }
            MultiVaultEventType::SharePriceChanged(_) => {
                "0xcc9bc63a4b047be4850fcbada8d7ed7aa097ed4f6c3b55bebc7e108ea1d2f824"
            }
            MultiVaultEventType::TripleCreated(_) => {
                "0xf13505b910c49b286cf7fbaf1a78620cf7d8bda0e8e39c1baed620c08af686e7"
            }
        }
    }

    pub fn event_name(&self) -> &'static str {
        match self {
            MultiVaultEventType::AtomCreated(_) => "AtomCreated",
            MultiVaultEventType::Deposited(_) => "Deposited",
            MultiVaultEventType::ProtocolFeeAccrued(_) => "ProtocolFeeAccrued",
            MultiVaultEventType::Redeemed(_) => "Redeemed",
            MultiVaultEventType::SharePriceChanged(_) => "SharePriceChanged",
            MultiVaultEventType::TripleCreated(_) => "TripleCreated",
        }
    }

    pub fn contract_name(&self) -> String {
        "MultiVault".to_string()
    }

    async fn get_provider(&self, network: &str) -> Arc<JsonRpcCachedProvider> {
        get_provider_cache_for_network(network).await
    }

    fn decoder(
        &self,
        network: &str,
    ) -> Arc<dyn Fn(Vec<B256>, Bytes) -> Arc<dyn Any + Send + Sync> + Send + Sync> {
        let decoder_contract = decoder_contract(network);

        match self {
            MultiVaultEventType::AtomCreated(_) => Arc::new(
                move |topics: Vec<B256>, data: Bytes| match AtomCreatedData::decode_raw_log(
                    topics,
                    &data[0..],
                ) {
                    Ok(event) => {
                        let result: AtomCreatedData = event;
                        Arc::new(result) as Arc<dyn Any + Send + Sync>
                    }
                    Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                },
            ),

            MultiVaultEventType::Deposited(_) => {
                Arc::new(
                    move |topics: Vec<B256>, data: Bytes| match DepositedData::decode_raw_log(
                        topics,
                        &data[0..],
                    ) {
                        Ok(event) => {
                            let result: DepositedData = event;
                            Arc::new(result) as Arc<dyn Any + Send + Sync>
                        }
                        Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                    },
                )
            }

            MultiVaultEventType::ProtocolFeeAccrued(_) => {
                Arc::new(move |topics: Vec<B256>, data: Bytes| {
                    match ProtocolFeeAccruedData::decode_raw_log(topics, &data[0..]) {
                        Ok(event) => {
                            let result: ProtocolFeeAccruedData = event;
                            Arc::new(result) as Arc<dyn Any + Send + Sync>
                        }
                        Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                    }
                })
            }

            MultiVaultEventType::Redeemed(_) => Arc::new(move |topics: Vec<B256>, data: Bytes| {
                match RedeemedData::decode_raw_log(topics, &data[0..]) {
                    Ok(event) => {
                        let result: RedeemedData = event;
                        Arc::new(result) as Arc<dyn Any + Send + Sync>
                    }
                    Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                }
            }),

            MultiVaultEventType::SharePriceChanged(_) => {
                Arc::new(move |topics: Vec<B256>, data: Bytes| {
                    match SharePriceChangedData::decode_raw_log(topics, &data[0..]) {
                        Ok(event) => {
                            let result: SharePriceChangedData = event;
                            Arc::new(result) as Arc<dyn Any + Send + Sync>
                        }
                        Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                    }
                })
            }

            MultiVaultEventType::TripleCreated(_) => {
                Arc::new(move |topics: Vec<B256>, data: Bytes| {
                    match TripleCreatedData::decode_raw_log(topics, &data[0..]) {
                        Ok(event) => {
                            let result: TripleCreatedData = event;
                            Arc::new(result) as Arc<dyn Any + Send + Sync>
                        }
                        Err(error) => Arc::new(error) as Arc<dyn Any + Send + Sync>,
                    }
                })
            }
        }
    }

    pub async fn register(self, manifest_path: &PathBuf, registry: &mut EventCallbackRegistry) {
        let rindexer_yaml = read_manifest(manifest_path).expect("Failed to read rindexer.yaml");
        let topic_id = self.topic_id();
        let contract_name = self.contract_name();
        let event_name = self.event_name();

        let contract_details = rindexer_yaml
            .all_contracts()
            .iter()
            .find(|c| c.name == contract_name)
            .unwrap_or_else(|| {
                panic!(
                    "Contract {} not found please make sure its defined in the rindexer.yaml",
                    contract_name
                )
            })
            .clone();

        let index_event_in_order = contract_details
            .index_event_in_order
            .as_ref()
            .is_some_and(|vec| vec.contains(&event_name.to_string()));

        // Expect providers to have been initialized, but it's an async init so this should
        // be fast but for correctness we must await each future.
        let mut providers = HashMap::new();
        for n in contract_details.details.iter() {
            let provider = self.get_provider(&n.network).await;
            providers.insert(n.network.clone(), provider);
        }

        let contract = ContractInformation {
            name: contract_details
                .before_modify_name_if_filter_readonly()
                .into_owned(),
            details: contract_details
                .details
                .iter()
                .map(|c| {
                    let provider = providers
                        .get(&c.network)
                        .expect("must have a provider")
                        .clone();

                    NetworkContract {
                        id: generate_random_id(10),
                        network: c.network.clone(),
                        cached_provider: provider.clone(),
                        block_clock: BlockClock::new(
                            rindexer_yaml.timestamps,
                            rindexer_yaml.config.timestamp_sample_rate,
                            provider.clone(),
                        ),
                        decoder: self.decoder(&c.network),
                        indexing_contract_setup: c.indexing_contract_setup(manifest_path),
                        start_block: c.start_block,
                        end_block: c.end_block,
                        disable_logs_bloom_checks: rindexer_yaml
                            .networks
                            .iter()
                            .find(|n| n.name == c.network)
                            .map(|n| n.disable_logs_bloom_checks.unwrap_or_default())
                            .unwrap_or(false),
                    }
                })
                .collect(),
            abi: contract_details.abi,
            reorg_safe_distance: contract_details.reorg_safe_distance.unwrap_or_default(),
        };

        let callback: Arc<
            dyn Fn(Vec<EventResult>) -> BoxFuture<'static, EventCallbackResult<()>> + Send + Sync,
        > = match self {
            MultiVaultEventType::AtomCreated(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }

            MultiVaultEventType::Deposited(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }

            MultiVaultEventType::ProtocolFeeAccrued(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }

            MultiVaultEventType::Redeemed(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }

            MultiVaultEventType::SharePriceChanged(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }

            MultiVaultEventType::TripleCreated(event) => {
                let event = Arc::new(event);
                Arc::new(move |result| {
                    let event = Arc::clone(&event);
                    async move { event.call(result).await }.boxed()
                })
            }
        };

        registry.register_event(EventCallbackRegistryInformation {
            id: generate_random_id(10),
            indexer_name: "be_v3_indexer".to_string(),
            event_name: event_name.to_string(),
            index_event_in_order,
            topic_id: topic_id.parse::<B256>().unwrap(),
            contract,
            callback,
        });
    }
}
