// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import {
	bigint,
	index,
	integer,
	numeric,
	pgTable,
	primaryKey,
	text,
	timestamp,
} from 'drizzle-orm/pg-core';

export const account = pgTable(
	'account',
	{
		accountId: text('account_id').primaryKey(),
		firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(),
		lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
		accountType: text('account_type').notNull().default('Default'),
		accountLabel: text('account_label'),
		accountImage: text('account_image'),
	},
	(table) => ({
		idxAccountLastSeen: index('idx_account_last_seen').on(table.lastSeenAt),
		idxAccountType: index('idx_account_type').on(table.accountType),
	})
);

export const activeVaultPosition = pgTable(
	'active_vault_position',
	{
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		accountId: text('account_id').notNull(),
		shares: numeric('shares').notNull(),
		totalDeposits: numeric('total_deposits').notNull(),
		totalRedemptions: numeric('total_redemptions').notNull(),
		openedAt: timestamp('opened_at', { withTimezone: true }),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		activeVaultPositionPkey: primaryKey({
			columns: [table.termId, table.curveId, table.accountId],
		}),
		idxAvpAccount: index('idx_avp_account').on(table.accountId),
		idxAvpTermCurve: index('idx_avp_term_curve').on(table.termId, table.curveId),
	})
);

export const dirtyAccount = pgTable('dirty_account', {
	accountId: text('account_id').primaryKey(),
	reason: text('reason'),
	firstMarkedAt: timestamp('first_marked_at', { withTimezone: true }).notNull().defaultNow(),
	lastMarkedAt: timestamp('last_marked_at', { withTimezone: true }).notNull().defaultNow(),
});

export const accountStats = pgTable('account_stats', {
	accountId: text('account_id').primaryKey(),
	totalPositionCount: integer('total_position_count').notNull().default(0),
	activePositionCount: integer('active_position_count').notNull().default(0),
	totalDeposits: numeric('total_deposits').notNull(),
	totalRedemptions: numeric('total_redemptions').notNull(),
	totalVolume: numeric('total_volume').notNull(),
	firstPositionAt: timestamp('first_position_at', { withTimezone: true }),
	lastActivityAt: timestamp('last_activity_at', { withTimezone: true }),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const accountPnlState = pgTable('account_pnl_state', {
	accountId: text('account_id').primaryKey(),
	totalDeposits: numeric('total_deposits').notNull(),
	totalRedemptions: numeric('total_redemptions').notNull(),
	realizedPnl: numeric('realized_pnl').notNull(),
	unrealizedPnl: numeric('unrealized_pnl').notNull(),
	totalPnl: numeric('total_pnl').notNull(),
	currentEquityValue: numeric('current_equity_value').notNull(),
	winningPositions: integer('winning_positions').notNull().default(0),
	losingPositions: integer('losing_positions').notNull().default(0),
	lastRecomputedAt: timestamp('last_recomputed_at', { withTimezone: true }),
	sourceWatermark: bigint('source_watermark', { mode: 'bigint' }).notNull(),
});

export const accountPnlSnapshot = pgTable(
	'account_pnl_snapshot',
	{
		accountId: text('account_id').notNull(),
		totalDeposits: numeric('total_deposits').notNull(),
		totalRedemptions: numeric('total_redemptions').notNull(),
		realizedPnl: numeric('realized_pnl').notNull(),
		unrealizedPnl: numeric('unrealized_pnl').notNull(),
		totalPnl: numeric('total_pnl').notNull(),
		currentEquityValue: numeric('current_equity_value').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxApsAccount: index('idx_aps_account').on(table.accountId, table.ts),
	})
);
