// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import {
	bigint,
	bigserial,
	boolean,
	index,
	integer,
	jsonb,
	numeric,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';

export const projectionCheckpoints = pgTable(
	'projection_checkpoints',
	{
		checkpointKey: text('checkpoint_key').primaryKey(),
		projectionName: text('projection_name').notNull(),
		sinkName: text('sink_name').notNull(),
		lastSequenceNumber: bigint('last_sequence_number', { mode: 'bigint' }).notNull(),
		lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		lastUpdatedAt: timestamp('last_updated_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		projectionCheckpointsUnique1: uniqueIndex('projection_checkpoints_unique_1').on(
			table.projectionName,
			table.sinkName
		),
	})
);

export const eventStore = pgTable(
	'event_store',
	{
		sequenceNumber: bigserial('sequence_number', { mode: 'bigint' }).notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		eventType: text('event_type').notNull(),
		eventData: jsonb('event_data').notNull(),
		termId: text('term_id'),
		entityId: text('entity_id'),
		isCanonical: boolean('is_canonical').notNull().default(true),
		ingestedAt: timestamp('ingested_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		eventStorePkey: primaryKey({ columns: [table.blockTimestamp, table.sequenceNumber] }),
		eventStoreUnique1: uniqueIndex('event_store_unique_1').on(
			table.transactionHash,
			table.logIndex,
			table.blockTimestamp
		),
		idxEventBlock: index('idx_event_block').on(table.blockNumber),
		idxEventEntityId: index('idx_event_entity_id').on(table.entityId, table.blockTimestamp),
		idxEventSequence: index('idx_event_sequence').on(table.sequenceNumber),
		idxEventTermId: index('idx_event_term_id').on(table.termId, table.blockTimestamp),
		idxEventType: index('idx_event_type').on(table.eventType, table.sequenceNumber),
	})
);

export const event = pgTable(
	'event',
	{
		eventId: text('event_id').primaryKey(),
		eventType: text('event_type').notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxEventBlock: index('idx_event_block').on(table.blockNumber),
		idxEventTypeTs: index('idx_event_type_ts').on(table.eventType, table.ts),
	})
);

export const depositFact = pgTable(
	'deposit_fact',
	{
		eventId: text('event_id').primaryKey(),
		senderId: text('sender_id').notNull(),
		receiverId: text('receiver_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		vaultType: integer('vault_type'),
		assets: numeric('assets').notNull(),
		assetsAfterFees: numeric('assets_after_fees').notNull(),
		shares: numeric('shares').notNull(),
		totalShares: numeric('total_shares').notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxDepositFactSender: index('idx_deposit_fact_sender').on(table.senderId, table.ts),
		idxDepositFactTerm: index('idx_deposit_fact_term').on(table.termId, table.ts),
	})
);

export const redemptionFact = pgTable(
	'redemption_fact',
	{
		eventId: text('event_id').primaryKey(),
		senderId: text('sender_id').notNull(),
		receiverId: text('receiver_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		vaultType: integer('vault_type'),
		shares: numeric('shares').notNull(),
		totalShares: numeric('total_shares').notNull(),
		assets: numeric('assets').notNull(),
		fees: numeric('fees').notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxRedemptionFactSender: index('idx_redemption_fact_sender').on(table.senderId, table.ts),
		idxRedemptionFactTerm: index('idx_redemption_fact_term').on(table.termId, table.ts),
	})
);

export const feeTransferFact = pgTable(
	'fee_transfer_fact',
	{
		eventId: text('event_id').primaryKey(),
		senderId: text('sender_id').notNull(),
		amount: numeric('amount').notNull(),
		epoch: text('epoch'),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxFeeTransferSender: index('idx_fee_transfer_sender').on(table.senderId, table.ts),
	})
);

export const atomCreatedEvents = pgTable(
	'atom_created_events',
	{
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		creator: text('creator').notNull(),
		termId: numeric('term_id').notNull(),
		atomData: text('atom_data').notNull(),
		atomWallet: text('atom_wallet').notNull(),
		sequenceNumber: bigint('sequence_number', { mode: 'bigint' }).notNull(),
		termIdHex: text('term_id_hex').notNull(),
	},
	(table) => ({
		atomCreatedEventsPkey: primaryKey({ columns: [table.transactionHash, table.logIndex] }),
		idxAtomCreatedCreator: index('idx_atom_created_creator').on(
			table.creator,
			table.blockTimestamp
		),
		idxAtomCreatedTerm: index('idx_atom_created_term').on(table.termId),
		uxAtomCreatedSeq: uniqueIndex('ux_atom_created_seq').on(table.sequenceNumber),
	})
);

export const tripleCreatedEvents = pgTable(
	'triple_created_events',
	{
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		creator: text('creator').notNull(),
		termId: numeric('term_id').notNull(),
		subjectId: numeric('subject_id').notNull(),
		predicateId: numeric('predicate_id').notNull(),
		objectId: numeric('object_id').notNull(),
		sequenceNumber: bigint('sequence_number', { mode: 'bigint' }).notNull(),
		termIdHex: text('term_id_hex').notNull(),
		subjectIdHex: text('subject_id_hex').notNull(),
		predicateIdHex: text('predicate_id_hex').notNull(),
		objectIdHex: text('object_id_hex').notNull(),
	},
	(table) => ({
		tripleCreatedEventsPkey: primaryKey({ columns: [table.transactionHash, table.logIndex] }),
		idxTripleCreatedCreator: index('idx_triple_created_creator').on(
			table.creator,
			table.blockTimestamp
		),
		idxTripleCreatedSubject: index('idx_triple_created_subject').on(table.subjectId),
		idxTripleCreatedTerm: index('idx_triple_created_term').on(table.termId),
		uxTripleCreatedSeq: uniqueIndex('ux_triple_created_seq').on(table.sequenceNumber),
	})
);

export const depositedEvents = pgTable(
	'deposited_events',
	{
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		sender: text('sender').notNull(),
		receiver: text('receiver').notNull(),
		termId: numeric('term_id').notNull(),
		curveId: numeric('curve_id').notNull(),
		assets: numeric('assets').notNull(),
		assetsAfterFees: numeric('assets_after_fees').notNull(),
		shares: numeric('shares').notNull(),
		totalShares: numeric('total_shares').notNull(),
		vaultType: integer('vault_type').notNull(),
		sequenceNumber: bigint('sequence_number', { mode: 'bigint' }).notNull(),
		termIdHex: text('term_id_hex').notNull(),
	},
	(table) => ({
		depositedEventsPkey: primaryKey({
			columns: [table.blockTimestamp, table.transactionHash, table.logIndex],
		}),
		idxDepositedReceiver: index('idx_deposited_receiver').on(table.receiver, table.blockTimestamp),
		idxDepositedSender: index('idx_deposited_sender').on(table.sender, table.blockTimestamp),
		idxDepositedSeq: index('idx_deposited_seq').on(table.sequenceNumber),
		idxDepositedTerm: index('idx_deposited_term').on(table.termId, table.blockTimestamp),
		uxDepositedTxLog: uniqueIndex('ux_deposited_tx_log').on(
			table.transactionHash,
			table.logIndex,
			table.blockTimestamp
		),
	})
);

export const redeemedEvents = pgTable(
	'redeemed_events',
	{
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		sender: text('sender').notNull(),
		receiver: text('receiver').notNull(),
		termId: numeric('term_id').notNull(),
		curveId: numeric('curve_id').notNull(),
		shares: numeric('shares').notNull(),
		totalShares: numeric('total_shares').notNull(),
		assets: numeric('assets').notNull(),
		fees: numeric('fees').notNull(),
		vaultType: integer('vault_type').notNull(),
		sequenceNumber: bigint('sequence_number', { mode: 'bigint' }).notNull(),
		termIdHex: text('term_id_hex').notNull(),
	},
	(table) => ({
		redeemedEventsPkey: primaryKey({
			columns: [table.blockTimestamp, table.transactionHash, table.logIndex],
		}),
		idxRedeemedReceiver: index('idx_redeemed_receiver').on(table.receiver, table.blockTimestamp),
		idxRedeemedSender: index('idx_redeemed_sender').on(table.sender, table.blockTimestamp),
		idxRedeemedSeq: index('idx_redeemed_seq').on(table.sequenceNumber),
		idxRedeemedTerm: index('idx_redeemed_term').on(table.termId, table.blockTimestamp),
		uxRedeemedTxLog: uniqueIndex('ux_redeemed_tx_log').on(
			table.transactionHash,
			table.logIndex,
			table.blockTimestamp
		),
	})
);

export const sharePriceChangedEvents = pgTable(
	'share_price_changed_events',
	{
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		termId: numeric('term_id').notNull(),
		curveId: numeric('curve_id').notNull(),
		sharePrice: numeric('share_price').notNull(),
		totalAssets: numeric('total_assets').notNull(),
		totalShares: numeric('total_shares').notNull(),
		vaultType: integer('vault_type').notNull(),
		sequenceNumber: bigint('sequence_number', { mode: 'bigint' }).notNull(),
		termIdHex: text('term_id_hex').notNull(),
	},
	(table) => ({
		sharePriceChangedEventsPkey: primaryKey({
			columns: [table.blockTimestamp, table.transactionHash, table.logIndex],
		}),
		idxSpcSeq: index('idx_spc_seq').on(table.sequenceNumber),
		idxSpcTermCurve: index('idx_spc_term_curve').on(
			table.termId,
			table.curveId,
			table.blockTimestamp
		),
		uxSharePriceChangedTxLog: uniqueIndex('ux_share_price_changed_tx_log').on(
			table.transactionHash,
			table.logIndex,
			table.blockTimestamp
		),
	})
);

export const protocolFeeAccruedEvents = pgTable(
	'protocol_fee_accrued_events',
	{
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		blockHash: text('block_hash').notNull(),
		transactionHash: text('transaction_hash').notNull(),
		logIndex: integer('log_index').notNull(),
		epoch: numeric('epoch').notNull(),
		sender: text('sender').notNull(),
		amount: numeric('amount').notNull(),
		sequenceNumber: bigint('sequence_number', { mode: 'bigint' }).notNull(),
	},
	(table) => ({
		protocolFeeAccruedEventsPkey: primaryKey({ columns: [table.transactionHash, table.logIndex] }),
		idxProtocolFeeEpoch: index('idx_protocol_fee_epoch').on(table.epoch),
		idxProtocolFeeSender: index('idx_protocol_fee_sender').on(table.sender, table.blockTimestamp),
		idxProtocolFeeSeq: index('idx_protocol_fee_seq').on(table.sequenceNumber),
	})
);
