// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import {
	bigint,
	index,
	integer,
	numeric,
	pgTable,
	primaryKey,
	text,
	timestamp,
} from 'drizzle-orm/pg-core';

export const leaderboardCache = pgTable(
	'leaderboard_cache',
	{
		cacheVersion: integer('cache_version').notNull(),
		period: text('period').notNull(),
		sortKey: text('sort_key').notNull(),
		rank: integer('rank').notNull(),
		accountId: text('account_id').notNull(),
		accountLabel: text('account_label'),
		accountImage: text('account_image'),
		totalPnlRaw: numeric('total_pnl_raw').notNull(),
		totalPnlFormatted: numeric('total_pnl_formatted').notNull(),
		realizedPnlRaw: numeric('realized_pnl_raw').notNull(),
		realizedPnlFormatted: numeric('realized_pnl_formatted').notNull(),
		unrealizedPnlRaw: numeric('unrealized_pnl_raw').notNull(),
		unrealizedPnlFormatted: numeric('unrealized_pnl_formatted').notNull(),
		pnlPct: numeric('pnl_pct').notNull(),
		realizedPnlPct: numeric('realized_pnl_pct').notNull(),
		unrealizedPnlPct: numeric('unrealized_pnl_pct').notNull(),
		pnlChangeRaw: numeric('pnl_change_raw').notNull(),
		pnlChangeFormatted: numeric('pnl_change_formatted').notNull(),
		totalPositionCount: bigint('total_position_count', { mode: 'bigint' }).notNull(),
		activePositionCount: bigint('active_position_count', { mode: 'bigint' }).notNull(),
		winningPositions: bigint('winning_positions', { mode: 'bigint' }).notNull(),
		losingPositions: bigint('losing_positions', { mode: 'bigint' }).notNull(),
		winRate: numeric('win_rate').notNull(),
		totalDepositsRaw: numeric('total_deposits_raw').notNull(),
		totalDepositsFormatted: numeric('total_deposits_formatted').notNull(),
		totalRedemptionsRaw: numeric('total_redemptions_raw').notNull(),
		totalRedemptionsFormatted: numeric('total_redemptions_formatted').notNull(),
		totalVolumeRaw: numeric('total_volume_raw').notNull(),
		totalVolumeFormatted: numeric('total_volume_formatted').notNull(),
		currentEquityValueRaw: numeric('current_equity_value_raw').notNull(),
		currentEquityValueFormatted: numeric('current_equity_value_formatted').notNull(),
		bestTradePnlRaw: numeric('best_trade_pnl_raw'),
		bestTradePnlFormatted: numeric('best_trade_pnl_formatted'),
		worstTradePnlRaw: numeric('worst_trade_pnl_raw'),
		worstTradePnlFormatted: numeric('worst_trade_pnl_formatted'),
		redeemableAssetsRaw: numeric('redeemable_assets_raw'),
		redeemableAssetsFormatted: numeric('redeemable_assets_formatted'),
		firstPositionAt: timestamp('first_position_at', { withTimezone: true }),
		lastActivityAt: timestamp('last_activity_at', { withTimezone: true }),
		computedAt: timestamp('computed_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		leaderboardCachePkey: primaryKey({
			columns: [table.cacheVersion, table.period, table.sortKey, table.rank],
		}),
		idxLcPeriodSort: index('idx_lc_period_sort').on(
			table.period,
			table.sortKey,
			table.cacheVersion
		),
	})
);

export const leaderboardCacheVersion = pgTable(
	'leaderboard_cache_version',
	{
		period: text('period').notNull(),
		sortKey: text('sort_key').notNull(),
		activeVersion: integer('active_version').notNull().default(0),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		leaderboardCacheVersionPkey: primaryKey({ columns: [table.period, table.sortKey] }),
	})
);
