// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import {
	bigint,
	index,
	integer,
	numeric,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';

export const position = pgTable(
	'position',
	{
		accountId: text('account_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		shares: numeric('shares').notNull(),
		totalDeposits: numeric('total_deposits').notNull(),
		totalDepositsValue: numeric('total_deposits_value').notNull(),
		totalSharesAcquired: numeric('total_shares_acquired').notNull(),
		costBasis: numeric('cost_basis').notNull(),
		realizedPnl: numeric('realized_pnl').notNull(),
		openedAt: timestamp('opened_at', { withTimezone: true }),
		closedAt: timestamp('closed_at', { withTimezone: true }),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
		version: integer('version').notNull().default(0),
	},
	(table) => ({
		positionPkey: primaryKey({ columns: [table.accountId, table.termId, table.curveId] }),
		idxPositionAccount: index('idx_position_account').on(table.accountId),
		idxPositionTerm: index('idx_position_term').on(table.termId, table.curveId),
	})
);

export const positionChange = pgTable(
	'position_change',
	{
		eventId: text('event_id').notNull(),
		accountId: text('account_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		eventType: text('event_type').notNull(),
		sharesDelta: numeric('shares_delta').notNull(),
		assetsIn: numeric('assets_in').notNull(),
		assetsOut: numeric('assets_out').notNull(),
		executionPrice: numeric('execution_price').notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxPcAccount: index('idx_pc_account').on(table.accountId, table.ts),
		idxPcEventId: uniqueIndex('idx_pc_event_id').on(table.eventId, table.ts),
		idxPcTerm: index('idx_pc_term').on(table.termId, table.curveId, table.ts),
	})
);

export const positionCumulativeHourly = pgTable(
	'position_cumulative_hourly',
	{
		bucket: timestamp('bucket', { withTimezone: true }).notNull(),
		accountId: text('account_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		cumulativeShares: numeric('cumulative_shares').notNull(),
		cumulativeAssetsIn: numeric('cumulative_assets_in').notNull(),
		cumulativeAssetsOut: numeric('cumulative_assets_out').notNull(),
		cumulativeSharesIn: numeric('cumulative_shares_in').notNull(),
		cumulativeSharesOut: numeric('cumulative_shares_out').notNull(),
	},
	(table) => ({
		idxPcumhPk: uniqueIndex('idx_pcumh_pk').on(
			table.accountId,
			table.termId,
			table.curveId,
			table.bucket
		),
		idxPcumhTerm: index('idx_pcumh_term').on(table.termId, table.curveId, table.bucket),
	})
);
