// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import { bigint, index, numeric, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const signal = pgTable(
	'signal',
	{
		eventId: text('event_id').notNull(),
		accountId: text('account_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		signalType: text('signal_type').notNull(),
		delta: numeric('delta').notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxSignalAccount: index('idx_signal_account').on(table.accountId, table.ts),
		idxSignalTerm: index('idx_signal_term').on(table.termId, table.curveId, table.ts),
		idxSignalType: index('idx_signal_type').on(table.signalType, table.ts),
	})
);
