// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import { bigint, integer, numeric, pgTable, timestamp } from 'drizzle-orm/pg-core';

export const stats = pgTable('stats', {
	id: integer('id').default(1).primaryKey(),
	totalAtoms: bigint('total_atoms', { mode: 'bigint' }).notNull(),
	totalTriples: bigint('total_triples', { mode: 'bigint' }).notNull(),
	totalAccounts: bigint('total_accounts', { mode: 'bigint' }).notNull(),
	totalDepositsCount: bigint('total_deposits_count', { mode: 'bigint' }).notNull(),
	totalRedemptionsCount: bigint('total_redemptions_count', { mode: 'bigint' }).notNull(),
	totalDepositVolume: numeric('total_deposit_volume').notNull(),
	totalRedemptionVolume: numeric('total_redemption_volume').notNull(),
	totalFees: numeric('total_fees').notNull(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const statsHistory = pgTable('stats_history', {
	totalAtoms: bigint('total_atoms', { mode: 'bigint' }).notNull(),
	totalTriples: bigint('total_triples', { mode: 'bigint' }).notNull(),
	totalAccounts: bigint('total_accounts', { mode: 'bigint' }).notNull(),
	totalDepositsCount: bigint('total_deposits_count', { mode: 'bigint' }).notNull(),
	totalRedemptionsCount: bigint('total_redemptions_count', { mode: 'bigint' }).notNull(),
	totalDepositVolume: numeric('total_deposit_volume').notNull(),
	totalRedemptionVolume: numeric('total_redemption_volume').notNull(),
	totalFees: numeric('total_fees').notNull(),
	ts: timestamp('ts', { withTimezone: true }).notNull(),
});
