// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import {
	bigint,
	index,
	integer,
	numeric,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';

export const term = pgTable(
	'term',
	{
		termId: text('term_id').primaryKey(),
		termType: text('term_type').notNull(),
		creator: text('creator').notNull(),
		atomData: text('atom_data'),
		atomDataHex: text('atom_data_hex'),
		subjectId: text('subject_id'),
		predicateId: text('predicate_id'),
		objectId: text('object_id'),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		blockTimestamp: timestamp('block_timestamp', { withTimezone: true }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
	},
	(table) => ({
		idxTermCreator: index('idx_term_creator').on(table.creator),
		idxTermObject: index('idx_term_object').on(table.objectId),
		idxTermPredicate: index('idx_term_predicate').on(table.predicateId),
		idxTermSubject: index('idx_term_subject').on(table.subjectId),
		idxTermType: index('idx_term_type').on(table.termType),
	})
);

export const termSummary = pgTable('term_summary', {
	termId: text('term_id').primaryKey(),
	termType: text('term_type').notNull(),
	totalAssets: numeric('total_assets').notNull(),
	totalMarketCap: numeric('total_market_cap').notNull(),
	totalHolderCount: integer('total_holder_count').notNull().default(0),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const termMarketCapHistory = pgTable(
	'term_market_cap_history',
	{
		termId: text('term_id').notNull(),
		totalAssets: numeric('total_assets').notNull(),
		totalMarketCap: numeric('total_market_cap').notNull(),
		totalHolderCount: integer('total_holder_count').notNull().default(0),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
		eventId: text('event_id'),
	},
	(table) => ({
		idxTmchEventId: uniqueIndex('idx_tmch_event_id').on(table.eventId, table.ts),
		idxTmchTerm: index('idx_tmch_term').on(table.termId, table.ts),
	})
);

export const predicateObjectSummary = pgTable(
	'predicate_object_summary',
	{
		predicateId: text('predicate_id').notNull(),
		objectId: text('object_id').notNull(),
		tripleCount: integer('triple_count').notNull().default(0),
		totalAssets: numeric('total_assets').notNull(),
		totalMarketCap: numeric('total_market_cap').notNull(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		predicateObjectSummaryPkey: primaryKey({ columns: [table.predicateId, table.objectId] }),
	})
);

export const subjectPredicateSummary = pgTable(
	'subject_predicate_summary',
	{
		subjectId: text('subject_id').notNull(),
		predicateId: text('predicate_id').notNull(),
		tripleCount: integer('triple_count').notNull().default(0),
		totalAssets: numeric('total_assets').notNull(),
		totalMarketCap: numeric('total_market_cap').notNull(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		subjectPredicateSummaryPkey: primaryKey({ columns: [table.subjectId, table.predicateId] }),
	})
);
