// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts
// Source of truth: backend/migrations/*.sql

import {
	bigint,
	index,
	integer,
	numeric,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uniqueIndex,
} from 'drizzle-orm/pg-core';

export const vault = pgTable(
	'vault',
	{
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		totalShares: numeric('total_shares').notNull(),
		currentSharePrice: numeric('current_share_price').notNull(),
		totalAssets: numeric('total_assets').notNull(),
		totalDeposits: numeric('total_deposits').notNull(),
		totalRedemptions: numeric('total_redemptions').notNull(),
		marketCap: numeric('market_cap').notNull(),
		holderCount: integer('holder_count').notNull().default(0),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		vaultPkey: primaryKey({ columns: [table.termId, table.curveId] }),
	})
);

export const sharePriceHistory = pgTable(
	'share_price_history',
	{
		eventId: text('event_id').notNull(),
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		sharePrice: numeric('share_price').notNull(),
		totalAssets: numeric('total_assets').notNull(),
		totalShares: numeric('total_shares').notNull(),
		marketCap: numeric('market_cap').notNull(),
		blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
		transactionHash: text('transaction_hash').notNull(),
		ts: timestamp('ts', { withTimezone: true }).notNull(),
	},
	(table) => ({
		idxSphEventId: uniqueIndex('idx_sph_event_id').on(table.eventId, table.ts),
		idxSphTermCurve: index('idx_sph_term_curve').on(table.termId, table.curveId, table.ts),
	})
);

export const dirtyVault = pgTable(
	'dirty_vault',
	{
		termId: text('term_id').notNull(),
		curveId: text('curve_id').notNull(),
		firstMarkedAt: timestamp('first_marked_at', { withTimezone: true }).notNull().defaultNow(),
		lastMarkedAt: timestamp('last_marked_at', { withTimezone: true }).notNull().defaultNow(),
	},
	(table) => ({
		dirtyVaultPkey: primaryKey({ columns: [table.termId, table.curveId] }),
	})
);
