import { timescaleFileGroups } from './layout';
import type {
	ColumnDefault,
	ColumnDefinition,
	CompatInventory,
	ManifestTable,
	TableDefinition,
} from './types';

export function renderSchemaFile(tables: TableDefinition[]): string {
	const importNames = new Set<string>(['pgTable']);

	for (const table of tables) {
		for (const column of table.columns) {
			importNames.add(getBuilderName(column));
		}

		if (table.primaryKey.length > 1) {
			importNames.add('primaryKey');
		}

		if (table.indexes.some((index) => index.unique)) {
			importNames.add('uniqueIndex');
		}

		if (table.indexes.some((index) => !index.unique)) {
			importNames.add('index');
		}

		if (table.uniqueConstraints.length > 0) {
			importNames.add('uniqueIndex');
		}
	}

	const imports = [...importNames].sort().join(',\n\t');
	const renderedTables = tables.map((table) => renderTable(table)).join('\n\n');

	return `// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts\n// Source of truth: backend/migrations/*.sql\n\nimport {\n\t${imports},\n} from 'drizzle-orm/pg-core';\n\n${renderedTables}\n`;
}

export function renderIndexFile(): string {
	const exportLines = timescaleFileGroups.map(
		(group) => `export * from './${group.fileName.replace(/\.ts$/, '')}';`
	);
	return `// Generated by packages/database-timescale/scripts/generate-timescale-schema.ts\n\n${exportLines.join('\n')}\n`;
}

export function renderManifest(tables: Map<string, TableDefinition>): string {
	const manifest = {
		tables: [...tables.values()]
			.sort((left, right) => left.name.localeCompare(right.name))
			.map<ManifestTable>((table) => ({
				columns: table.columns.map((column) => ({
					name: column.name,
					notNull: column.notNull,
					precision: column.precision,
					scale: column.scale,
					type: column.type,
				})),
				name: table.name,
				primaryKey: table.primaryKey,
			})),
	};

	return `${JSON.stringify(manifest, null, 2)}\n`;
}

export function renderCompatInventory(compatInventory: CompatInventory): string {
	const sortedInventory = {
		continuousAggregates: [...compatInventory.continuousAggregates].sort(),
		functions: [...compatInventory.functions].sort(),
		hypertables: [...compatInventory.hypertables].sort(),
		jobs: [...compatInventory.jobs].sort(),
		materializedViews: [...compatInventory.materializedViews].sort(),
		types: [...compatInventory.types].sort(),
		views: [...compatInventory.views].sort(),
	};

	return `${JSON.stringify(sortedInventory, null, 2)}\n`;
}

function renderTable(table: TableDefinition): string {
	const hasCallback =
		table.primaryKey.length > 1 || table.indexes.length > 0 || table.uniqueConstraints.length > 0;
	const renderedColumns = table.columns
		.map((column) => `\t\t${toCamelCase(column.name)}: ${renderColumn(column, table.primaryKey)},`)
		.join('\n');

	if (!hasCallback) {
		return `export const ${toCamelCase(table.name)} = pgTable(\n\t'${table.name}',\n\t{\n${renderedColumns}\n\t}\n);`;
	}

	const callbackEntries: string[] = [];

	if (table.primaryKey.length > 1) {
		callbackEntries.push(
			`\t\t${toCamelCase(`${table.name}_pkey`)}: primaryKey({ columns: [${table.primaryKey
				.map((columnName) => `table.${toCamelCase(columnName)}`)
				.join(', ')}] }),`
		);
	}

	for (const uniqueConstraint of [...table.uniqueConstraints].sort((left, right) =>
		left.name.localeCompare(right.name)
	)) {
		callbackEntries.push(
			`\t\t${toCamelCase(uniqueConstraint.name)}: uniqueIndex('${uniqueConstraint.name}').on(${uniqueConstraint.columns
				.map((columnName) => `table.${toCamelCase(columnName)}`)
				.join(', ')}),`
		);
	}

	for (const indexDefinition of [...table.indexes].sort((left, right) =>
		left.name.localeCompare(right.name)
	)) {
		const builder = indexDefinition.unique ? 'uniqueIndex' : 'index';
		callbackEntries.push(
			`\t\t${toCamelCase(indexDefinition.name)}: ${builder}('${indexDefinition.name}').on(${indexDefinition.columns
				.map((columnName) => `table.${toCamelCase(columnName)}`)
				.join(', ')}),`
		);
	}

	return `export const ${toCamelCase(table.name)} = pgTable(\n\t'${table.name}',\n\t{\n${renderedColumns}\n\t},\n\t(table) => ({\n${callbackEntries.join('\n')}\n\t})\n);`;
}

function renderColumn(column: ColumnDefinition, primaryKey: string[]): string {
	const builder = renderColumnBuilder(column);
	const chainedCalls: string[] = [];
	const isSingleColumnPrimaryKey = primaryKey.length === 1 && primaryKey[0] === column.name;

	if (column.notNull && !isSingleColumnPrimaryKey) {
		chainedCalls.push('notNull()');
	}

	if (column.defaultValue) {
		const renderedDefault = renderColumnDefault(column.defaultValue);
		if (renderedDefault) {
			chainedCalls.push(renderedDefault);
		}
	}

	if (isSingleColumnPrimaryKey) {
		if (!column.notNull) {
			chainedCalls.push('notNull()');
		}
		chainedCalls.push('primaryKey()');
	}

	return chainedCalls.reduce((value, chain) => `${value}.${chain}`, builder);
}

function renderColumnBuilder(column: ColumnDefinition): string {
	switch (column.type) {
		case 'bigint':
			return `bigint('${column.name}', { mode: 'bigint' })`;
		case 'bigserial':
			return `bigserial('${column.name}', { mode: 'bigint' })`;
		case 'boolean':
			return `boolean('${column.name}')`;
		case 'integer':
			return `integer('${column.name}')`;
		case 'jsonb':
			return `jsonb('${column.name}')`;
		case 'numeric':
			if (column.precision) {
				const scale = column.scale ?? 0;
				return `numeric('${column.name}', { precision: ${column.precision}, scale: ${scale} })`;
			}
			return `numeric('${column.name}')`;
		case 'text':
			return `text('${column.name}')`;
		case 'timestamptz':
			return `timestamp('${column.name}', { withTimezone: true })`;
		default:
			throw new Error(`Unsupported builder for column type ${(column as ColumnDefinition).type}`);
	}
}

function renderColumnDefault(defaultValue: ColumnDefault): string | undefined {
	switch (defaultValue.kind) {
		case 'boolean':
			return `default(${defaultValue.value ? 'true' : 'false'})`;
		case 'integer':
			return `default(${defaultValue.value})`;
		case 'now':
			return 'defaultNow()';
		case 'text':
			return `default(${JSON.stringify(defaultValue.value)})`;
		default:
			return undefined;
	}
}

function getBuilderName(column: ColumnDefinition): string {
	switch (column.type) {
		case 'bigint':
			return 'bigint';
		case 'bigserial':
			return 'bigserial';
		case 'boolean':
			return 'boolean';
		case 'integer':
			return 'integer';
		case 'jsonb':
			return 'jsonb';
		case 'numeric':
			return 'numeric';
		case 'text':
			return 'text';
		case 'timestamptz':
			return 'timestamp';
		default:
			throw new Error(`Unsupported import for column type ${column.type}`);
	}
}

function toCamelCase(value: string): string {
	return value.replace(/_([a-z0-9])/g, (_, character: string) => character.toUpperCase());
}
