import {
	type ClassificationDefinition,
	type ClassificationRegistry,
	createClassificationRegistry,
} from './registry';
import {
	aiEntitiesDataSchema,
	aiSummaryDataSchema,
	appleMusicDataSchema,
	arxivDataSchema,
	brandDataSchema,
	classificationSlugSchema,
	colorPaletteDataSchema,
	companyProfileDataSchema,
	crunchbaseDataSchema,
	dictionaryDataSchema,
	doiDataSchema,
	ensDataSchema,
	etherscanDataSchema,
	faviconDataSchema,
	geocodeDataSchema,
	githubRepoDataSchema,
	githubUserDataSchema,
	isbnDataSchema,
	microdataDataSchema,
	musicbrainzDataSchema,
	nftMetadataDataSchema,
	npmPackageDataSchema,
	oembedDataSchema,
	opengraphDataSchema,
	placesDataSchema,
	productListingDataSchema,
	pubmedDataSchema,
	redditPostDataSchema,
	screenshotDataSchema,
	spotifyDataSchema,
	tmdbDataSchema,
	tokenMetadataDataSchema,
	vimeoDataSchema,
	wikidataDataSchema,
	wikipediaDataSchema,
	xProfileDataSchema,
	youtubeDataSchema,
} from './schemas';

export const builtinClassificationDefinitions = [
	{
		slug: 'opengraph',
		displayName: 'OpenGraph Metadata',
		category: 'web-metadata',
		dataSchema: opengraphDataSchema,
		renderer: 'OpenGraphCard',
		description: 'URL metadata extracted from OpenGraph tags.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'oembed',
		displayName: 'oEmbed Embed',
		category: 'web-metadata',
		dataSchema: oembedDataSchema,
		renderer: 'OEmbedCard',
		description: 'Provider-supplied rich embed metadata from oEmbed endpoints.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'microdata',
		displayName: 'Structured Microdata',
		category: 'web-metadata',
		dataSchema: microdataDataSchema,
		renderer: 'MicrodataCard',
		description: 'Structured metadata extracted from JSON-LD and microdata markup.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'favicon',
		displayName: 'Site Favicon',
		category: 'web-metadata',
		dataSchema: faviconDataSchema,
		renderer: 'FaviconCard',
		description: 'Canonical favicon metadata for the target site.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'screenshot',
		displayName: 'Page Screenshot',
		category: 'web-metadata',
		dataSchema: screenshotDataSchema,
		renderer: 'ScreenshotCard',
		description: 'Rendered screenshot capture and viewport metadata.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'brand',
		displayName: 'Brand Identity',
		category: 'brand-identity',
		dataSchema: brandDataSchema,
		renderer: 'BrandCard',
		description: 'Logo, color palette, and identity metadata for a domain.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'company-profile',
		displayName: 'Company Profile',
		category: 'brand-identity',
		dataSchema: companyProfileDataSchema,
		renderer: 'CompanyProfileCard',
		description: 'Normalized organization profile from company data providers.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'wikipedia',
		displayName: 'Wikipedia Summary',
		category: 'knowledge',
		dataSchema: wikipediaDataSchema,
		renderer: 'WikipediaCard',
		description: 'Article summary and metadata sourced from Wikipedia.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'wikidata',
		displayName: 'Wikidata Entity',
		category: 'knowledge',
		dataSchema: wikidataDataSchema,
		renderer: 'WikidataCard',
		description: 'Wikidata entity claims, identifiers, and sitelinks.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'dictionary',
		displayName: 'Dictionary Definition',
		category: 'knowledge',
		dataSchema: dictionaryDataSchema,
		renderer: 'DictionaryCard',
		description: 'Dictionary meanings, pronunciation, and lexical metadata.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'places',
		displayName: 'Place Details',
		category: 'location',
		dataSchema: placesDataSchema,
		renderer: 'PlacesCard',
		description: 'Place profile metadata including location, ratings, and contact data.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'geocode',
		displayName: 'Geocode Result',
		category: 'location',
		dataSchema: geocodeDataSchema,
		renderer: 'GeocodeCard',
		description: 'Geocoding coordinates and normalized address components.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'spotify',
		displayName: 'Spotify Metadata',
		category: 'music',
		dataSchema: spotifyDataSchema,
		renderer: 'SpotifyCard',
		description: 'Spotify track, album, or artist metadata.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'apple-music',
		displayName: 'Apple Music Metadata',
		category: 'music',
		dataSchema: appleMusicDataSchema,
		renderer: 'AppleMusicCard',
		description: 'Apple Music song, album, or artist metadata.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'musicbrainz',
		displayName: 'MusicBrainz Entry',
		category: 'music',
		dataSchema: musicbrainzDataSchema,
		renderer: 'MusicBrainzCard',
		description: 'Open music database entity metadata.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'youtube',
		displayName: 'YouTube Video',
		category: 'video',
		dataSchema: youtubeDataSchema,
		renderer: 'YouTubeCard',
		description: 'YouTube video metadata and engagement stats.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'vimeo',
		displayName: 'Vimeo Video',
		category: 'video',
		dataSchema: vimeoDataSchema,
		renderer: 'VimeoCard',
		description: 'Vimeo video metadata and embed details.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'tmdb',
		displayName: 'Movie/TV Metadata',
		category: 'video',
		dataSchema: tmdbDataSchema,
		renderer: 'TmdbCard',
		description: 'TMDB metadata for movie and TV entities.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'github-repo',
		displayName: 'GitHub Repository',
		category: 'social',
		dataSchema: githubRepoDataSchema,
		renderer: 'GitHubRepoCard',
		description: 'Repository metadata from GitHub.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'github-user',
		displayName: 'GitHub User Profile',
		category: 'social',
		dataSchema: githubUserDataSchema,
		renderer: 'GitHubUserCard',
		description: 'User profile metadata from GitHub.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'npm-package',
		displayName: 'NPM Package',
		category: 'social',
		dataSchema: npmPackageDataSchema,
		renderer: 'NpmPackageCard',
		description: 'NPM package registry metadata.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'x-profile',
		displayName: 'X Profile',
		category: 'social',
		dataSchema: xProfileDataSchema,
		renderer: 'XProfileCard',
		description: 'Profile metadata for an X account.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'reddit-post',
		displayName: 'Reddit Post',
		category: 'social',
		dataSchema: redditPostDataSchema,
		renderer: 'RedditPostCard',
		description: 'Post metadata sourced from Reddit APIs.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'crunchbase',
		displayName: 'Crunchbase Company',
		category: 'financial',
		dataSchema: crunchbaseDataSchema,
		renderer: 'CrunchbaseCard',
		description: 'Funding and company profile metadata from Crunchbase.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'doi',
		displayName: 'DOI Publication',
		category: 'academic',
		dataSchema: doiDataSchema,
		renderer: 'DoiCard',
		description: 'DOI publication metadata from CrossRef/DataCite.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'arxiv',
		displayName: 'arXiv Paper',
		category: 'academic',
		dataSchema: arxivDataSchema,
		renderer: 'ArxivCard',
		description: 'Preprint metadata from arXiv.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'pubmed',
		displayName: 'PubMed Article',
		category: 'academic',
		dataSchema: pubmedDataSchema,
		renderer: 'PubmedCard',
		description: 'Biomedical publication metadata from PubMed.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'ens',
		displayName: 'ENS Name',
		category: 'blockchain',
		dataSchema: ensDataSchema,
		renderer: 'EnsCard',
		description: 'ENS record metadata and address resolution.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'etherscan',
		displayName: 'Etherscan Address',
		category: 'blockchain',
		dataSchema: etherscanDataSchema,
		renderer: 'EtherscanCard',
		description: 'Address and contract metadata from Etherscan.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'nft-metadata',
		displayName: 'NFT Metadata',
		category: 'blockchain',
		dataSchema: nftMetadataDataSchema,
		renderer: 'NftMetadataCard',
		description: 'NFT collection and token metadata.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'token-metadata',
		displayName: 'Token Metadata',
		category: 'blockchain',
		dataSchema: tokenMetadataDataSchema,
		renderer: 'TokenMetadataCard',
		description: 'Fungible token metadata, pricing, and identifiers.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'color-palette',
		displayName: 'Color Palette',
		category: 'image',
		dataSchema: colorPaletteDataSchema,
		renderer: 'ColorPaletteCard',
		description: 'Image-derived dominant colors and palette breakdown.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'product-listing',
		displayName: 'Product Listing',
		category: 'product',
		dataSchema: productListingDataSchema,
		renderer: 'ProductListingCard',
		description: 'Product catalog metadata including pricing and availability.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'isbn',
		displayName: 'ISBN Book Lookup',
		category: 'product',
		dataSchema: isbnDataSchema,
		renderer: 'IsbnCard',
		description: 'Book metadata from ISBN lookup services.',
		schemaVersion: '1.0.0',
		runtime: 'universal',
	},
	{
		slug: 'ai-summary',
		displayName: 'AI-Generated Summary',
		category: 'ai',
		dataSchema: aiSummaryDataSchema,
		renderer: 'AiSummaryCard',
		description: 'Generated summary payloads from AI providers.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
	{
		slug: 'ai-entities',
		displayName: 'AI Entity Extraction',
		category: 'ai',
		dataSchema: aiEntitiesDataSchema,
		renderer: 'AiEntitiesCard',
		description: 'Named entity extraction output from AI providers.',
		schemaVersion: '1.0.0',
		runtime: 'server',
	},
] as const satisfies readonly ClassificationDefinition[];

for (const definition of builtinClassificationDefinitions) {
	classificationSlugSchema.parse(definition.slug);
}

export type RegisterBuiltinClassificationsOptions = {
	override?: boolean;
};

export function registerBuiltinClassifications(
	registry: ClassificationRegistry,
	options?: RegisterBuiltinClassificationsOptions
): ClassificationRegistry {
	for (const definition of builtinClassificationDefinitions) {
		registry.register(definition, { override: options?.override });
	}

	return registry;
}

export function createDefaultClassificationRegistry(): ClassificationRegistry {
	const registry = createClassificationRegistry();
	registerBuiltinClassifications(registry);
	return registry;
}

export function listBuiltinClassificationSlugs(): string[] {
	return builtinClassificationDefinitions.map((definition) => definition.slug).sort();
}
