export {
	builtinClassificationDefinitions,
	createDefaultClassificationRegistry,
	listBuiltinClassificationSlugs,
	registerBuiltinClassifications,
} from './defaults';
export type {
	ClassificationDefinition,
	ClassificationRegistry,
	RegisterClassificationOptions,
} from './registry';
export { createClassificationRegistry } from './registry';
export type {
	AiEntitiesData,
	AiSummaryData,
	AppleMusicData,
	ArxivData,
	BrandData,
	ClassificationCategory,
	ColorPaletteData,
	CompanyProfileData,
	CrunchbaseData,
	DictionaryData,
	DoiData,
	EnsData,
	EtherscanData,
	FaviconData,
	GeocodeData,
	GitHubRepoData,
	GitHubUserData,
	IsbnData,
	MicrodataData,
	MusicBrainzData,
	NftMetadataData,
	NpmPackageData,
	OEmbedData,
	OpenGraphData,
	PlacesData,
	ProductListingData,
	PubmedData,
	RedditPostData,
	ScreenshotData,
	SpotifyData,
	TmdbData,
	TokenMetadataData,
	VimeoData,
	WikidataData,
	WikipediaData,
	XProfileData,
	YouTubeData,
} from './schemas';
export {
	aiEntitiesDataSchema,
	aiSummaryDataSchema,
	appleMusicDataSchema,
	arxivDataSchema,
	brandDataSchema,
	classificationCategorySchema,
	classificationSlugSchema,
	colorPaletteDataSchema,
	companyProfileDataSchema,
	crunchbaseDataSchema,
	dictionaryDataSchema,
	doiDataSchema,
	ensDataSchema,
	etherscanDataSchema,
	faviconDataSchema,
	geocodeDataSchema,
	githubRepoDataSchema,
	githubUserDataSchema,
	isbnDataSchema,
	microdataDataSchema,
	musicbrainzDataSchema,
	nftMetadataDataSchema,
	npmPackageDataSchema,
	oembedDataSchema,
	opengraphDataSchema,
	placesDataSchema,
	productListingDataSchema,
	pubmedDataSchema,
	redditPostDataSchema,
	screenshotDataSchema,
	spotifyDataSchema,
	tmdbDataSchema,
	tokenMetadataDataSchema,
	vimeoDataSchema,
	wikidataDataSchema,
	wikipediaDataSchema,
	xProfileDataSchema,
	youtubeDataSchema,
} from './schemas';
